relation_templates = {
    "IsA": [
        {"question": "A is a type of what?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which category does A belong to?", "choice": ["C1","B","C2","C3"]},
        {"question": "A can be classified as what?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept includes A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A falls under which category?", "choice": ["B","C2","C3","C1"]},
        {"question": "A is considered a type of what?", "choice": ["C1","B","C3","C2"]},
        {"question": "Under which group can A be categorized?", "choice": ["C3","C2","B","C1"]},
        {"question": "Which larger concept includes A?", "choice": ["B","C3","C1","C2"]},
        {"question": "What general category includes A?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which class does A belong to?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is a kind of what?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which class does A fall under?", "choice": ["C3","B","C1","C2"]},
        {"question": "A belongs to which category?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which type includes A?", "choice": ["B","C1","C2","C3"]},
        {"question": "A is part of which class?", "choice": ["C1","B","C3","C2"]},
        {"question": "Under which classification does A belong?", "choice": ["C2","C1","B","C3"]},
        {"question": "Which group contains A?", "choice": ["C3","C1","C2","B"]},
        {"question": "A can be grouped as what?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which general type does A belong to?", "choice": ["C1","B","C3","C2"]},
        {"question": "A falls under which class?", "choice": ["C2","C3","B","C1"]},
        {"question": "What kind of category includes A?", "choice": ["C3","C2","B","C1"]},
        {"question": "A can be classified into which group?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which larger class includes A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A belongs to what type?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which group does A fall under?", "choice": ["C3","C1","C2","B"]},
        {"question": "A can be assigned to which category?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which system includes A?", "choice": ["C1","B","C2","C3"]},
        {"question": "A is classified under which class?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which class encompasses A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A is a member of which category?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which type does A belong to?", "choice": ["C1","C2","B","C3"]},
        {"question": "A falls into which group?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which class is A part of?", "choice": ["C3","C1","C2","B"]},
        {"question": "A can be considered part of which category?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which kind includes A?", "choice": ["C1","B","C3","C2"]},
        {"question": "A can be included in which class?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which larger category contains A?", "choice": ["C3","C1","C2","B"]},
        {"question": "A belongs to which classification?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which category encompasses A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A can be grouped into which type?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which class is A classified under?", "choice": ["C3","C2","B","C1"]},
        {"question": "A falls under what classification?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which general group does A belong to?", "choice": ["C1","B","C3","C2"]},
        {"question": "A is categorized under which class?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which category is A part of?", "choice": ["C3","B","C1","C2"]},
        {"question": "A is included in which type?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which group encompasses A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A can be considered under which class?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which system does A belong to?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is part of which group?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which type is A included in?", "choice": ["C1","C3","B","C2"]},
        {"question": "A can be classified into which type?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which category does A fall under?", "choice": ["C3","C2","B","C1"]},
        {"question": "A is grouped under which classification?", "choice": ["B","C1","C2","C3"]}
    ],
    "Synonym": [
        {"question": "Which concept is similar to A?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which concept is synonymous with A?", "choice": ["C1","B","C2","C3"]},
        {"question": "Which concept can also be called A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can also refer to which concept?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which concept has a meaning closest to A?", "choice": ["B","C2","C3","C1"]},
        {"question": "A is another word for what?", "choice": ["C1","B","C3","C2"]},
        {"question": "Which concept expresses the same idea as A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can be replaced with which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept has the same meaning as A?", "choice": ["B","C3","C1","C2"]},
        {"question": "A is equivalent to which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept is an alternative to A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A can be interchanged with which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept conveys the same meaning as A?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which word has the closest meaning to A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A can also be described by which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept represents the same idea as A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A and which concept have similar meanings?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which concept can substitute for A?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept is another name for A?", "choice": ["C2","B","C1","C3"]},
        {"question": "A can also mean which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept expresses a similar idea to A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A can be referred to by which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept is equivalent to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is closely related to which concept in meaning?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which concept could replace A in a sentence?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which concept conveys a meaning similar to A?", "choice": ["C1","B","C3","C2"]},
        {"question": "A can also stand for which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept has the same sense as A?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept is interchangeable with A?", "choice": ["B","C1","C2","C3"]},
        {"question": "A is another term for which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept can represent the same idea as A?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which concept expresses a meaning closest to A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A can be referred to as which concept?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which concept conveys the same notion as A?", "choice": ["C1","B","C3","C2"]},
        {"question": "A is a synonym of which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept can A be substituted with?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which concept has meaning equivalent to A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A can also be expressed by which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept shares meaning with A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A and which concept are semantically similar?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept is another expression of A?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which concept means the same as A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A can also signify which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept has a synonym relationship with A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is conceptually similar to which other concept?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which concept could be used in place of A?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept has meaning closest to A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A can be interchanged with which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept represents the meaning of A?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which concept conveys a concept similar to A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A can also be referred to as which concept?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which concept has a meaning equivalent to A?", "choice": ["C3","C1","B","C2"]}
    ],
    "CapableOf": [
        {"question": "What can A do?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which action can A perform?", "choice": ["C1","B","C2","C3"]},
        {"question": "A is capable of which activity?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which action is associated with A?", "choice": ["C3","B","C1","C2"]},
        {"question": "What is A able to do?", "choice": ["B","C2","C3","C1"]},
        {"question": "A can carry out which action?", "choice": ["C1","B","C3","C2"]},
        {"question": "Which task can A perform?", "choice": ["C2","C3","B","C1"]},
        {"question": "A has the ability to do what?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which activity can A accomplish?", "choice": ["B","C3","C1","C2"]},
        {"question": "A can execute which action?", "choice": ["C1","C2","B","C3"]},
        {"question": "What activities is A capable of?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which action can be done by A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A can perform which task?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which operation can A carry out?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is able to perform which action?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which capability belongs to A?", "choice": ["C3","B","C2","C1"]},
        {"question": "What can A achieve?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is equipped to do what?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which activity can A undertake?", "choice": ["C2","B","C3","C1"]},
        {"question": "A can engage in which action?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which action is A capable of?", "choice": ["B","C2","C1","C3"]},
        {"question": "A has the capacity to do what?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which thing can A do?", "choice": ["C2","B","C3","C1"]},
        {"question": "A can undertake which task?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which action can be performed by A?", "choice": ["B","C2","C3","C1"]},
        {"question": "What is within A's abilities?", "choice": ["C1","B","C2","C3"]},
        {"question": "Which task can A carry out?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can do which operation?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which action can A complete?", "choice": ["B","C2","C1","C3"]},
        {"question": "A can perform which activity?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which activity is within A's capabilities?", "choice": ["C2","C3","B","C1"]},
        {"question": "What action can A accomplish?", "choice": ["C3","B","C2","C1"]},
        {"question": "A can execute which task?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which task can A undertake?", "choice": ["C1","C2","B","C3"]},
        {"question": "What can A carry out?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is able to accomplish which action?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which activity can A perform?", "choice": ["B","C2","C1","C3"]},
        {"question": "A has the power to do what?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which operation is A capable of?", "choice": ["C2","B","C3","C1"]},
        {"question": "A can do which task?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which action is achievable by A?", "choice": ["B","C2","C3","C1"]},
        {"question": "A can carry out which activity?", "choice": ["C1","B","C2","C3"]},
        {"question": "What can A perform?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is able to execute which task?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which action can A successfully complete?", "choice": ["B","C2","C1","C3"]},
        {"question": "A can engage in which activity?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which task is within A's capability?", "choice": ["C2","C3","B","C1"]},
        {"question": "A has the ability to accomplish what?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which activity can A undertake successfully?", "choice": ["B","C1","C3","C2"]},
        {"question": "A can carry out which operation?", "choice": ["C1","C2","B","C3"]},
        {"question": "What actions can A perform?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is capable of undertaking which task?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which operation can A perform effectively?", "choice": ["B","C2","C1","C3"]}
    ],
    "AtLocation": [
        {"question": "Where is A typically found?", "choice": ["B","C1","C2","C3"]},
        {"question": "In which location can A be found?", "choice": ["C1","B","C2","C3"]},
        {"question": "A is commonly located where?", "choice": ["C2","C3","B","C1"]},
        {"question": "Where would you usually find A?", "choice": ["C3","B","C1","C2"]},
        {"question": "What is the usual location of A?", "choice": ["B","C2","C3","C1"]},
        {"question": "Where is A most likely found?", "choice": ["C1","B","C3","C2"]},
        {"question": "In which place does A commonly appear?", "choice": ["C2","C3","B","C1"]},
        {"question": "Where can one typically see A?", "choice": ["C3","B","C2","C1"]},
        {"question": "What is A's typical location?", "choice": ["B","C3","C1","C2"]},
        {"question": "Where would you expect to find A?", "choice": ["C1","C2","B","C3"]},
        {"question": "In what location is A usually found?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is often located where?", "choice": ["C3","C1","B","C2"]},
        {"question": "Where is A generally found?", "choice": ["B","C2","C1","C3"]},
        {"question": "In which area can A typically be found?", "choice": ["C1","C3","B","C2"]},
        {"question": "Where does A usually reside?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is situated where?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which location is A commonly associated with?", "choice": ["B","C1","C3","C2"]},
        {"question": "Where might you find A?", "choice": ["C1","C2","B","C3"]},
        {"question": "What is the common place for A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is normally found where?", "choice": ["C3","C1","B","C2"]},
        {"question": "In which environment is A typically located?", "choice": ["B","C2","C1","C3"]},
        {"question": "Where is A predominantly found?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which place usually contains A?", "choice": ["C2","C3","B","C1"]},
        {"question": "Where would you find A most often?", "choice": ["C3","B","C1","C2"]},
        {"question": "A is generally located in which place?", "choice": ["B","C1","C2","C3"]},
        {"question": "What location is associated with A?", "choice": ["C1","B","C3","C2"]},
        {"question": "Where does A normally occur?", "choice": ["C2","C3","B","C1"]},
        {"question": "Where can A typically be observed?", "choice": ["C3","B","C2","C1"]},
        {"question": "In what place is A commonly found?", "choice": ["B","C3","C1","C2"]},
        {"question": "Where might A be located?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is often seen at which location?", "choice": ["C2","B","C3","C1"]},
        {"question": "Where is A generally seen?", "choice": ["C3","C1","B","C2"]},
        {"question": "In which spot can A be found?", "choice": ["B","C2","C1","C3"]},
        {"question": "Where is A commonly situated?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which area usually contains A?", "choice": ["C2","C3","B","C1"]},
        {"question": "Where is A typically located?", "choice": ["C3","B","C2","C1"]},
        {"question": "In what environment is A usually found?", "choice": ["B","C1","C3","C2"]},
        {"question": "Where would A normally be found?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is commonly seen where?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which location is A typically associated with?", "choice": ["C3","C1","B","C2"]},
        {"question": "Where is the usual place to find A?", "choice": ["B","C2","C1","C3"]},
        {"question": "In which setting is A commonly found?", "choice": ["C1","C3","B","C2"]},
        {"question": "Where might A typically be observed?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can be found in which usual place?", "choice": ["C3","B","C1","C2"]},
        {"question": "What is the frequent location of A?", "choice": ["B","C1","C2","C3"]},
        {"question": "Where is A predominantly situated?", "choice": ["C1","B","C3","C2"]},
        {"question": "In what place is A often located?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is usually present where?", "choice": ["C3","B","C2","C1"]},
        {"question": "Where is A commonly found most often?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which location generally contains A?", "choice": ["C1","C2","B","C3"]},
        {"question": "Where would A typically appear?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is usually located at which place?", "choice": ["C3","B","C1","C2"]}
    ],
    "HasProperty": [
        {"question": "What property does A have?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which characteristic describes A?", "choice": ["C1","B","C2","C3"]},
        {"question": "A is known for which property?", "choice": ["C2","C3","B","C1"]},
        {"question": "What attribute is associated with A?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which feature does A possess?", "choice": ["B","C2","C3","C1"]},
        {"question": "A has which quality?", "choice": ["C1","B","C3","C2"]},
        {"question": "Which property is typical of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A exhibits which characteristic?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which trait belongs to A?", "choice": ["B","C3","C1","C2"]},
        {"question": "A possesses which feature?", "choice": ["C1","C2","B","C3"]},
        {"question": "What is a property of A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A has which distinguishing feature?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which quality is A known for?", "choice": ["B","C2","C1","C3"]},
        {"question": "What attribute does A display?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is characterized by which property?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which feature is typical for A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A possesses what trait?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which property is associated with A?", "choice": ["C1","C2","B","C3"]},
        {"question": "What characteristic does A exhibit?", "choice": ["C2","B","C3","C1"]},
        {"question": "A has what attribute?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which quality is commonly seen in A?", "choice": ["B","C2","C1","C3"]},
        {"question": "What trait does A have?", "choice": ["C1","C3","B","C2"]},
        {"question": "A exhibits which property?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which feature can be found in A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is identified by which characteristic?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which attribute is associated with A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is noted for which quality?", "choice": ["C2","C3","B","C1"]},
        {"question": "What feature is A known for?", "choice": ["C3","B","C1","C2"]},
        {"question": "A possesses which distinguishing property?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which characteristic belongs to A?", "choice": ["C1","C3","B","C2"]},
        {"question": "What attribute is typical of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A displays which quality?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which feature characterizes A?", "choice": ["B","C1","C3","C2"]},
        {"question": "What property can be observed in A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is associated with which trait?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which attribute describes A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is known to have which feature?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which quality is a characteristic of A?", "choice": ["C1","C3","B","C2"]},
        {"question": "What trait can be linked to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A exhibits what attribute?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which property defines A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is typically characterized by which quality?", "choice": ["C1","C2","B","C3"]},
        {"question": "What is a distinguishing feature of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A possesses which notable trait?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which characteristic is seen in A?", "choice": ["B","C2","C1","C3"]},
        {"question": "What quality can A be described by?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is marked by which attribute?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which feature can be attributed to A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is distinguished by which property?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which trait is characteristic of A?", "choice": ["C1","C2","B","C3"]},
        {"question": "What attribute is associated with A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is defined by which quality?", "choice": ["C3","B","C1","C2"]}
    ],
    "PartOf": [
        {"question": "A is part of what?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which larger entity does A belong to?", "choice": ["C1","B","C2","C3"]},
        {"question": "A is a component of which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which whole includes A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A contributes to which larger structure?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which entity contains A?", "choice": ["C1","B","C3","C2"]},
        {"question": "A is included in which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which whole is A a part of?", "choice": ["C3","B","C2","C1"]},
        {"question": "A belongs to which bigger entity?", "choice": ["B","C3","C1","C2"]},
        {"question": "Which structure does A form a part of?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is a section of which whole?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which entity is A a component of?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is included as part of which concept?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which larger system contains A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A forms part of which entity?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which entity includes A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is a component within which whole?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which bigger concept does A belong to?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is part of which structure?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which whole entity contains A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A contributes to which whole?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which larger entity is A included in?", "choice": ["C1","C3","B","C2"]},
        {"question": "A belongs to which structure?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept encompasses A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is a member of which entity?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which larger structure does A form part of?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is included in which system?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which whole concept contains A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A forms a part of which entity?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which entity is composed of A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is included as a component in which whole?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which structure includes A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is part of which larger system?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which bigger entity encompasses A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A contributes to which concept?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which whole entity is A a part of?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is a member within which structure?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which larger system does A belong to?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is included as part of which entity?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is A a part of?", "choice": ["C3","B","C2","C1"]},
        {"question": "A belongs within which larger entity?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which structure is A a component of?", "choice": ["C1","C2","B","C3"]},
        {"question": "A contributes as part of which whole?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which entity contains A as a part?", "choice": ["C3","B","C1","C2"]},
        {"question": "A is incorporated in which structure?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which larger whole does A belong to?", "choice": ["C1","C3","B","C2"]},
        {"question": "A forms part of which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which entity is composed in part by A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is a segment of which larger entity?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which system incorporates A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is contained within which entity?", "choice": ["C2","C3","B","C1"]}
    ],
    "UsedFor": [
        {"question": "What is A used for?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which purpose does A serve?", "choice": ["C1","B","C2","C3"]},
        {"question": "A can be utilized for what?", "choice": ["C2","C3","B","C1"]},
        {"question": "For what function is A used?", "choice": ["C3","B","C1","C2"]},
        {"question": "A serves which purpose?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which task can A perform?", "choice": ["C1","B","C3","C2"]},
        {"question": "A is intended for which use?", "choice": ["C2","C3","B","C1"]},
        {"question": "What is the function of A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is used to accomplish what?", "choice": ["B","C3","C1","C2"]},
        {"question": "Which action can A be used for?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is applied to what?", "choice": ["C2","B","C3","C1"]},
        {"question": "What operation can A perform?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is employed for which purpose?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which function does A fulfill?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is useful for what?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which task is A intended for?", "choice": ["C3","B","C2","C1"]},
        {"question": "A can be utilized to perform what?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which purpose can A serve?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is designed for what function?", "choice": ["C2","B","C3","C1"]},
        {"question": "What can A be used to accomplish?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which use is A associated with?", "choice": ["B","C2","C1","C3"]},
        {"question": "A serves for which operation?", "choice": ["C1","C3","B","C2"]},
        {"question": "What is A intended to do?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can perform which function?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which application is A used for?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is useful in what way?", "choice": ["C1","C2","B","C3"]},
        {"question": "What task can be accomplished using A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is applied for which purpose?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which operation can A be used for?", "choice": ["B","C2","C1","C3"]},
        {"question": "A can serve which purpose?", "choice": ["C1","C3","B","C2"]},
        {"question": "For what is A typically used?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is intended to accomplish what?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which task can A be applied to?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is employed to do what?", "choice": ["C1","C2","B","C3"]},
        {"question": "What can be done with A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is designed to perform what?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which function can A serve?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is applied for which function?", "choice": ["C1","C3","B","C2"]},
        {"question": "What is A's intended purpose?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is capable of being used for what?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which purpose is A designed for?", "choice": ["B","C1","C3","C2"]},
        {"question": "A can be used to achieve what?", "choice": ["C1","C2","B","C3"]},
        {"question": "For what task is A typically used?", "choice": ["C2","C3","B","C1"]},
        {"question": "A serves to accomplish which function?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which application is associated with A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is designed to be used for what?", "choice": ["C1","C3","B","C2"]},
        {"question": "What operation can A be applied to?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is utilized to perform which action?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which function can be carried out using A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is intended for which specific purpose?", "choice": ["C1","C2","B","C3"]},
        {"question": "What is A applied to?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can be used effectively for what?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which task is A employed for?", "choice": ["B","C2","C1","C3"]}
    ],
    "CausesDesire": [
        {"question": "A causes the desire for what?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which desire is triggered by A?", "choice": ["C1","B","C2","C3"]},
        {"question": "A can lead to wanting what?", "choice": ["C2","C3","B","C1"]},
        {"question": "What desire does A induce?", "choice": ["C3","B","C1","C2"]},
        {"question": "A motivates the desire for which concept?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which goal or desire can A create?", "choice": ["C1","B","C3","C2"]},
        {"question": "A prompts the desire for what?", "choice": ["C2","C3","B","C1"]},
        {"question": "What does A inspire someone to want?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which wish is caused by A?", "choice": ["B","C3","C1","C2"]},
        {"question": "A leads to which desire?", "choice": ["C1","C2","B","C3"]},
        {"question": "What does A encourage the desire for?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is known to cause desire for which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which want is A responsible for?", "choice": ["B","C2","C1","C3"]},
        {"question": "A generates the desire for what?", "choice": ["C1","C3","B","C2"]},
        {"question": "What craving can A trigger?", "choice": ["C2","C3","B","C1"]},
        {"question": "A brings about desire for which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which longing is caused by A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A provokes the desire to obtain what?", "choice": ["C1","C2","B","C3"]},
        {"question": "What does A make people want?", "choice": ["C2","B","C3","C1"]},
        {"question": "A stimulates the desire for which thing?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which object of desire is A linked to?", "choice": ["B","C2","C1","C3"]},
        {"question": "A causes interest or desire in what?", "choice": ["C1","C3","B","C2"]},
        {"question": "What desire can be elicited by A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A inspires the desire to obtain what?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which want does A trigger?", "choice": ["B","C1","C3","C2"]},
        {"question": "A leads to the craving for what?", "choice": ["C1","C2","B","C3"]},
        {"question": "What does A make people wish for?", "choice": ["C2","C3","B","C1"]},
        {"question": "A provokes interest in which concept?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which desire is prompted by A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A encourages the longing for what?", "choice": ["C1","C3","B","C2"]},
        {"question": "What does A incite a desire for?", "choice": ["C2","C3","B","C1"]},
        {"question": "A motivates the craving for which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which yearning does A produce?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is linked to desire for what?", "choice": ["C1","C2","B","C3"]},
        {"question": "What wish can A inspire?", "choice": ["C2","B","C3","C1"]},
        {"question": "A causes wanting which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which longing is initiated by A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A triggers the desire to achieve what?", "choice": ["C1","C3","B","C2"]},
        {"question": "What desire is produced by A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A inspires the wish for what?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which craving does A lead to?", "choice": ["B","C1","C3","C2"]},
        {"question": "A brings about the desire for which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "What does A motivate someone to want?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is responsible for desire for what?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which desire can A generate?", "choice": ["B","C2","C1","C3"]},
        {"question": "A causes the want for which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "What does A provoke a desire for?", "choice": ["C2","C3","B","C1"]},
        {"question": "A stimulates wanting which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which wish is initiated by A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A leads to the longing for what?", "choice": ["C1","C2","B","C3"]}
    ],
    "ReceivesAction": [
        {"question": "What action is performed on A?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which action can A receive?", "choice": ["C1","B","C2","C3"]},
        {"question": "A is subject to which action?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which action is directed at A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A undergoes which action?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which treatment or action does A receive?", "choice": ["C1","B","C3","C2"]},
        {"question": "A experiences which action?", "choice": ["C2","C3","B","C1"]},
        {"question": "What is done to A?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which action affects A?", "choice": ["B","C3","C1","C2"]},
        {"question": "A is acted upon by which action?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which procedure is applied to A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is subject to what treatment or action?", "choice": ["C3","C1","B","C2"]},
        {"question": "What is performed on A?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which act is done to A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is involved in which action?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which operation is executed on A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A receives which specific action?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which activity is performed on A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is subjected to which act?", "choice": ["C2","B","C3","C1"]},
        {"question": "What treatment or action is applied to A?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which procedure affects A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A experiences which activity?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which act is directed at A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is the recipient of which action?", "choice": ["C3","B","C2","C1"]},
        {"question": "What is applied to A?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which action takes place on A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is subject to which procedure?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which operation is performed on A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A undergoes which specific activity?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which treatment is given to A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is acted upon in which way?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which activity is A subjected to?", "choice": ["C3","B","C2","C1"]},
        {"question": "A receives which procedure?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which act affects A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is engaged in which action?", "choice": ["C2","B","C3","C1"]},
        {"question": "What action is carried out on A?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which process involves A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A experiences which operation?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which act is applied to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is subject to which activity?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which procedure is directed at A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A receives which specific act?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which operation is A involved in?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is acted upon through which procedure?", "choice": ["C3","B","C1","C2"]},
        {"question": "What activity is performed on A?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which action is applied to A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A undergoes which treatment?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which process affects A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is engaged in which procedure?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which act is executed on A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A experiences which action or operation?", "choice": ["C2","C3","B","C1"]}
    ],
    "Antonym": [
        {"question": "Which concept is the opposite of A?", "choice": ["B","C1","C2","C3"]},
        {"question": "A is contrasted with which concept?", "choice": ["C1","B","C2","C3"]},
        {"question": "Which concept has the opposite meaning of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A and which concept are antonyms?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which concept is contrary to A?", "choice": ["B","C2","C3","C1"]},
        {"question": "A is opposed to which concept?", "choice": ["C1","B","C3","C2"]},
        {"question": "Which concept is the reverse of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is the opposite of which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept is contrary in meaning to A?", "choice": ["B","C3","C1","C2"]},
        {"question": "A and which concept are in opposition?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept has a meaning opposite to A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A contrasts with which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept is the antonym of A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is in contrast to which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept expresses the opposite of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A has the opposite meaning of which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept is the reverse meaning of A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is contrary to which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept is the semantic opposite of A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is the negation of which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept is in opposition to A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is antonymous with which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept has the opposite sense of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is counter to which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept expresses the contrary of A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A and which concept have opposite meanings?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept negates the meaning of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is the opposite term for which concept?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which concept is semantically opposed to A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A contradicts which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept has a meaning contrary to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is the reverse of which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept has an opposite meaning to A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is in semantic opposition to which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept is diametrically opposed to A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is the counter concept to which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept opposes A in meaning?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is contrary in sense to which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept is the antithesis of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A expresses the opposite meaning of which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept is the logical opposite of A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A contradicts the meaning of which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept is the negation of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is antithetical to which concept?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which concept stands in opposition to A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is the inverse of which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept contradicts A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is opposite in sense to which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept is the converse of A?", "choice": ["B","C1","C3","C2"]}
    ],
    "DefinedAs": [
        {"question": "How is A defined?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which definition corresponds to A?", "choice": ["C1","B","C2","C3"]},
        {"question": "A can be described as what?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which phrase defines A?", "choice": ["C3","B","C1","C2"]},
        {"question": "What is the meaning of A?", "choice": ["B","C2","C3","C1"]},
        {"question": "A is characterized as what?", "choice": ["C1","B","C3","C2"]},
        {"question": "Which statement defines A?", "choice": ["C2","C3","B","C1"]},
        {"question": "How would you describe A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A can be explained as what?", "choice": ["B","C3","C1","C2"]},
        {"question": "Which description fits A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is understood as what?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which phrase explains A?", "choice": ["C3","C1","B","C2"]},
        {"question": "What does A mean?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is known as what?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which term defines A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is referred to as what?", "choice": ["C3","B","C2","C1"]},
        {"question": "What is A called?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which explanation suits A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A can be identified as what?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which statement best defines A?", "choice": ["C3","C1","B","C2"]},
        {"question": "How is the concept A described?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which description matches A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is interpreted as what?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which definition applies to A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is exemplified as what?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which concept explains A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A can be stated as what?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which phrase best explains A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A is defined in which way?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which meaning is associated with A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A can be described using which term?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which explanation is correct for A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is understood to mean what?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which definition best fits A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is expressed as what?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which description defines A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is articulated as what?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which explanation corresponds to A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A can be phrased as what?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which statement suits the definition of A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is denoted as what?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which term best describes A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is explained as what?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept describes A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A is interpreted to mean what?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which phrase defines the concept A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A can be explained by which definition?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which description conveys A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is characterized by which definition?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which meaning best defines A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is represented as what?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which explanation describes A accurately?", "choice": ["C3","C1","B","C2"]}
    ],
    "SimilarTo": [
        {"question": "Which concept is similar to A?", "choice": ["B","C1","C2","C3"]},
        {"question": "A resembles which concept?", "choice": ["C1","B","C2","C3"]},
        {"question": "Which concept shares similarities with A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is comparable to which concept?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which concept has traits similar to A?", "choice": ["B","C2","C3","C1"]},
        {"question": "A is like which concept?", "choice": ["C1","B","C3","C2"]},
        {"question": "Which concept is closely related to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can be compared to which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept shares characteristics with A?", "choice": ["B","C3","C1","C2"]},
        {"question": "A is similar in meaning to which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept is alike A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A corresponds to which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept is equivalent to A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A has a likeness to which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept matches A in meaning?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can be equated with which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept is comparable to A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A has similar features to which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept shares meaning with A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A resembles which idea?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept has similarity to A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is akin to which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept is analogous to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can be likened to which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept shares traits with A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is comparable in meaning to which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept is similar in sense to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is close in meaning to which concept?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which concept is related to A in similarity?", "choice": ["B","C2","C1","C3"]},
        {"question": "A can be matched with which concept?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept has a likeness with A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is reminiscent of which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept is congruent with A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A has attributes similar to which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept aligns with A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is closely related to which concept?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which concept is like A in meaning?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is comparable to which idea?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept shares a likeness with A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can be considered similar to which concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept is akin to A in meaning?", "choice": ["B","C1","C3","C2"]},
        {"question": "A has similarity with which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept is equivalent in meaning to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A can be associated with which similar concept?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which concept resembles A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is comparable to which term?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which concept reflects similarity to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is related to which concept in similarity?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which concept is matched with A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A has analogous features with which concept?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which concept corresponds to A in similarity?", "choice": ["C2","B","C3","C1"]}
    ],
    "HasA": [
        {"question": "What does A have?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which component is part of A?", "choice": ["C1","B","C2","C3"]},
        {"question": "A possesses which item?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which attribute belongs to A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A contains which element?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which feature is included in A?", "choice": ["C1","B","C3","C2"]},
        {"question": "A is equipped with which component?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which part does A have?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is composed of which item?", "choice": ["B","C3","C1","C2"]},
        {"question": "Which object is associated with A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A contains which feature?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which component belongs to A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is characterized by which part?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which item is found in A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A has which property?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which element is contained in A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is associated with which feature?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which part is included in A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A possesses which feature?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which component is part of A's structure?", "choice": ["C3","C1","B","C2"]},
        {"question": "A contains which property?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which item belongs to A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is made up of which component?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which feature characterizes A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A has which element?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which component is present in A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is equipped with which part?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which attribute does A include?", "choice": ["C3","B","C1","C2"]},
        {"question": "A contains which object?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which element belongs to A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A possesses which component?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which feature is part of A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is characterized by which feature?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which part is associated with A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A contains which specific item?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which property belongs to A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is composed of which element?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which component forms part of A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A possesses which object?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which element is found in A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A has which characteristic?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which part constitutes A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A includes which component?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which attribute is associated with A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A is made of which part?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which feature is present in A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A has which item or part?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which element or component belongs to A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is associated with which item?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which object forms part of A?", "choice": ["C1","C2","B","C3"]}
    ],
    "MadeOf": [
        {"question": "What is A made of?", "choice": ["B","C1","C2","C3"]},
        {"question": "A consists of which material?", "choice": ["C1","B","C2","C3"]},
        {"question": "Which substance composes A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is constructed from which material?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which element forms A?", "choice": ["B","C2","C3","C1"]},
        {"question": "A is built from which substance?", "choice": ["C1","B","C3","C2"]},
        {"question": "Which material is used to make A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is composed of which elements?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which components make up A?", "choice": ["B","C3","C1","C2"]},
        {"question": "A contains which material?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which material constitutes A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is formed from which substance?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which element is part of A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is derived from which material?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which substance is found in A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A consists mainly of which material?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which material is present in A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is made up of which components?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which material makes up A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A contains which substance?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which element composes A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is constructed using which material?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which material is used in A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is made primarily of which substance?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which substance is essential to A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is composed mainly of which material?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which material is integral to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A consists of which parts?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which substance is included in A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is formed using which material?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which element is used to make A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A contains which component?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which material constitutes the main part of A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is built mainly from which substance?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which components form A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is composed of which basic material?", "choice": ["C3","C1","B","C2"]},
        {"question": "Which substance is used in constructing A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A consists of which building material?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which material contributes to A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is made out of which material?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which element is used in A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A contains which essential material?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which substance forms part of A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A is made primarily from which substance?", "choice": ["C3","B","C1","C2"]},
        {"question": "Which material is integral to forming A?", "choice": ["B","C2","C1","C3"]},
        {"question": "A is composed of which essential components?", "choice": ["C1","C3","B","C2"]},
        {"question": "Which substance constitutes A?", "choice": ["C2","C3","B","C1"]},
        {"question": "A consists largely of which material?", "choice": ["C3","B","C2","C1"]},
        {"question": "Which element is part of the composition of A?", "choice": ["B","C1","C3","C2"]},
        {"question": "A is formed of which main material?", "choice": ["C1","C2","B","C3"]},
        {"question": "Which material forms the base of A?", "choice": ["C2","B","C3","C1"]},
        {"question": "A is made using which key substance?", "choice": ["C3","C1","B","C2"]}
    ],
    "Causes": [
        {"question": "What does A cause?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which effect is caused by A?", "choice": ["C1","B","C2","C3"]},
        {"question": "A leads to which outcome?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which result follows from A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A brings about which effect?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which consequence is caused by A?", "choice": ["C1","B","C3","C2"]},
        {"question": "A produces which result?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which outcome occurs due to A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A triggers which effect?", "choice": ["B","C3","C1","C2"]},
        {"question": "Which effect results from A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A gives rise to which consequence?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which outcome is produced by A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is responsible for which effect?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which result is brought by A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A generates which outcome?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which effect is triggered by A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A causes which result?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which consequence arises from A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A leads to which consequence?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which outcome is linked to A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is the reason for which effect?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which result is caused by A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A produces which consequence?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which effect results from the action of A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A leads to which outcome or effect?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which consequence occurs due to A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A gives rise to which result?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which effect is linked to A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A causes which specific effect?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which outcome follows A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A triggers which consequence?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which result is a consequence of A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is responsible for which outcome?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which effect does A produce?", "choice": ["C1","C2","B","C3"]},
        {"question": "A brings about which result?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which consequence follows from A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A generates which effect?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which result is triggered by A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A causes which outcome or consequence?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which effect arises from A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A produces which effect or outcome?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which result is linked to A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A leads to which specific result?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which consequence does A bring?", "choice": ["C3","B","C1","C2"]},
        {"question": "A triggers which outcome?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which effect can be caused by A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is the cause of which result?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which outcome results from A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is responsible for which consequence?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which effect is produced by A?", "choice": ["C1","C2","B","C3"]}
    ],
    "Desires": [
        {"question": "What does A desire?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which goal does A want to achieve?", "choice": ["C1","B","C2","C3"]},
        {"question": "A has a wish for which outcome?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which object or state does A long for?", "choice": ["C3","B","C1","C2"]},
        {"question": "A wants which thing?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which aim is desired by A?", "choice": ["C1","B","C3","C2"]},
        {"question": "A seeks which outcome?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which result does A yearn for?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is hoping for which thing?", "choice": ["B","C3","C1","C2"]},
        {"question": "Which object does A wish to obtain?", "choice": ["C1","C2","B","C3"]},
        {"question": "A desires which goal?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which outcome is A seeking?", "choice": ["C3","C1","B","C2"]},
        {"question": "A longs for which object?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which state is wished for by A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A hopes to achieve which result?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which aim does A want?", "choice": ["C3","B","C2","C1"]},
        {"question": "A seeks to obtain which thing?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which goal is desired by A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A wants to accomplish which objective?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which object or outcome does A desire?", "choice": ["C3","C1","B","C2"]},
        {"question": "A has a wish for which thing?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which result is A aiming for?", "choice": ["C1","C3","B","C2"]},
        {"question": "A yearns for which goal?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which aim is A hoping to achieve?", "choice": ["C3","B","C2","C1"]},
        {"question": "A desires to obtain which object?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which outcome is longed for by A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A wants which result?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which object does A aim to get?", "choice": ["C3","B","C1","C2"]},
        {"question": "A hopes for which outcome?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which goal does A long for?", "choice": ["C1","C3","B","C2"]},
        {"question": "A desires which object or result?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which thing is A seeking?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is aiming for which goal?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which result does A hope to achieve?", "choice": ["C1","C2","B","C3"]},
        {"question": "A wants to attain which object?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which aim is A longing for?", "choice": ["C3","C1","B","C2"]},
        {"question": "A seeks which object or outcome?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which goal does A wish to achieve?", "choice": ["C1","C3","B","C2"]},
        {"question": "A hopes to get which thing?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which object or state is desired by A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A longs to achieve which result?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which outcome is A trying to obtain?", "choice": ["C1","C2","B","C3"]},
        {"question": "A aims for which object?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which goal is A hoping for?", "choice": ["C3","C1","B","C2"]},
        {"question": "A desires which outcome or objective?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which thing is A aiming to get?", "choice": ["C1","C3","B","C2"]},
        {"question": "A wants to achieve which result?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which object does A hope to obtain?", "choice": ["C3","B","C2","C1"]},
        {"question": "A seeks which aim?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which outcome or goal does A desire?", "choice": ["C1","C2","B","C3"]},
        {"question": "A longs to acquire which object?", "choice": ["C2","C3","B","C1"]}
    ],
    "DistinctFrom": [
        {"question": "How is A distinct from B?", "choice": ["B","C1","C2","C3"]},
        {"question": "Which concept differs from A?", "choice": ["C1","B","C2","C3"]},
        {"question": "A is unlike which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is not similar to A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A can be distinguished from which concept?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which concept contrasts with A?", "choice": ["C1","B","C3","C2"]},
        {"question": "A is different from which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is opposite to A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is not the same as which concept?", "choice": ["B","C3","C1","C2"]},
        {"question": "Which concept is unlike A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is separate from which concept?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which concept does A differ from?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is distinguished from which concept?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which concept is not A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is dissimilar to which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is distinct from A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A differs from which concept?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which concept is separate from A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is unlike which other concept?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which concept is contrasted with A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A can be told apart from which concept?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which concept is not like A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is opposite to which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is differentiated from A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is in contrast with which concept?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which concept is unlike A in nature?", "choice": ["C1","C2","B","C3"]},
        {"question": "A can be separated from which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is not identical to A?", "choice": ["C3","B","C1","C2"]},
        {"question": "A is not the same as which other concept?", "choice": ["B","C2","C3","C1"]},
        {"question": "Which concept contrasts with A in meaning?", "choice": ["C1","B","C2","C3"]},
        {"question": "A differs in which aspect from which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is clearly different from A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is distinct from which other concept?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which concept is not associated with A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A can be distinguished from which other concept?", "choice": ["C2","B","C3","C1"]},
        {"question": "Which concept is not similar in nature to A?", "choice": ["C3","C1","B","C2"]},
        {"question": "A is different in which way from which concept?", "choice": ["B","C2","C1","C3"]},
        {"question": "Which concept is separate and distinct from A?", "choice": ["C1","C3","B","C2"]},
        {"question": "A is not like which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is opposed to A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A differs from which other concept in meaning?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which concept is not the same as A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A contrasts with which concept?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is distinct from A in concept?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is unlike which concept in meaning?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which concept is different from A?", "choice": ["C1","C2","B","C3"]},
        {"question": "A is distinguished from which other concept in meaning?", "choice": ["C2","C3","B","C1"]},
        {"question": "Which concept is not equal to A?", "choice": ["C3","B","C2","C1"]},
        {"question": "A is dissimilar to which other concept?", "choice": ["B","C1","C3","C2"]},
        {"question": "Which concept is separate from A in meaning?", "choice": ["C1","C2","B","C3"]},
        {"question": "A differs from which concept in essence?", "choice": ["C2","C3","B","C1"]}
    ]
}