tf_relation_templates = {
    "IsA": [
        {"question": "Is A a type of B?", "answer": True},
        {"question": "Can A be classified as B?", "answer": True},
        {"question": "Does A belong to the category B?", "answer": True},
        {"question": "Is B an example of A?", "answer": False},
        {"question": "Is A not a kind of B?", "answer": False},
        {"question": "Is A generally considered a B?", "answer": True},
        {"question": "Would A be placed under B in classification?", "answer": True},
        {"question": "Is A recognized as a form of B?", "answer": True},
        {"question": "Is A categorized as B in most cases?", "answer": True},
        {"question": "Is A a member of the group B?", "answer": True},
        {"question": "Can A be seen as belonging to B?", "answer": True},
        {"question": "Does A fall under the class of B?", "answer": True},
        {"question": "Is A an instance of B?", "answer": True},
        {"question": "Would A be grouped within B?", "answer": True},
        {"question": "Can we consider A as part of B?", "answer": True},
        {"question": "Is A viewed as a B?", "answer": True},
        {"question": "Do people regard A as a kind of B?", "answer": True},
        {"question": "Does A fit the category of B?", "answer": True},
        {"question": "Is A properly defined as a B?", "answer": True},
        {"question": "Is A one example of B?", "answer": True},
        {"question": "Is it true that A is not a B?", "answer": False},
        {"question": "Is A unrelated to B as a category?", "answer": False},
        {"question": "Is A completely different from B?", "answer": False},
        {"question": "Is A never classified as B?", "answer": False},
        {"question": "Does A avoid belonging to B?", "answer": False},
        {"question": "Is B a specific instance of A?", "answer": False},
        {"question": "Is B a type of A?", "answer": False},
        {"question": "Is B categorized under A?", "answer": False},
        {"question": "Does B fall under the classification of A?", "answer": False},
        {"question": "Is B generally considered to be a form of A?", "answer": False},
        {"question": "Would most people say that A is not part of B?", "answer": False},
        {"question": "Is it incorrect to classify A as B?", "answer": False},
        {"question": "Does A exclude itself from being B?", "answer": False},
        {"question": "Would it be wrong to call A a B?", "answer": False},
        {"question": "Is B the broader category compared to A?", "answer": False},
        {"question": "Does A define B as a subset?", "answer": False},
        {"question": "Is B the group A belongs to?", "answer": False},
        {"question": "Is A more general than B?", "answer": False},
        {"question": "Is A too specific to be a B?", "answer": False},
        {"question": "Is A the parent concept of B?", "answer": False},
        {"question": "Does A act as a superclass of B?", "answer": False},
        {"question": "Is A a broader term than B?", "answer": False},
        {"question": "Is A what defines B?", "answer": False},
        {"question": "Is B always a type of A?", "answer": False},
        {"question": "Does B belong to A strictly?", "answer": False},
        {"question": "Is B often classified as A?", "answer": False},
        {"question": "Is B considered the same category as A?", "answer": False},
        {"question": "Is B a more general term than A?", "answer": False},
        {"question": "Is A and B exactly the same classification?", "answer": False},
        {"question": "Do A and B represent the same category?", "answer": False},
        {"question": "Is A identical in classification to B?", "answer": False}
    ],
    "Synonym": [
        {"question": "Do A and B have the same meaning?", "answer": True},
        {"question": "Are A and B synonymous terms?", "answer": True},
        {"question": "Can A be used in place of B?", "answer": True},
        {"question": "Is A another way to say B?", "answer": True},
        {"question": "Do A and B express the same idea?", "answer": True},
        {"question": "Are A and B similar in meaning?", "answer": True},
        {"question": "Would a dictionary list A as a synonym of B?", "answer": True},
        {"question": "Is A considered equivalent in meaning to B?", "answer": True},
        {"question": "Do A and B refer to the same concept?", "answer": True},
        {"question": "Is A commonly replaced by B in sentences?", "answer": True},
        {"question": "Can A and B be interchanged without changing meaning?", "answer": True},
        {"question": "Is B a synonym for A?", "answer": True},
        {"question": "Is A simply another word for B?", "answer": True},
        {"question": "Do A and B convey the same definition?", "answer": True},
        {"question": "Would A and B be grouped as synonyms?", "answer": True},
        {"question": "Are A and B linguistically equivalent?", "answer": True},
        {"question": "Could A substitute for B in most contexts?", "answer": True},
        {"question": "Do A and B belong to the same meaning group?", "answer": True},
        {"question": "Are A and B identical in meaning?", "answer": True},
        {"question": "Does A mean the same thing as B?", "answer": True},
        {"question": "Do A and B have unrelated meanings?", "answer": False},
        {"question": "Are A and B antonyms?", "answer": False},
        {"question": "Is A the opposite of B?", "answer": False},
        {"question": "Does A contradict the meaning of B?", "answer": False},
        {"question": "Is A unrelated to B in meaning?", "answer": False},
        {"question": "Do A and B never share meaning?", "answer": False},
        {"question": "Is A not similar to B?", "answer": False},
        {"question": "Are A and B opposite concepts?", "answer": False},
        {"question": "Does A define the reverse of B?", "answer": False},
        {"question": "Are A and B contradictory in meaning?", "answer": False},
        {"question": "Would it be wrong to say A and B mean the same?", "answer": False},
        {"question": "Does A always differ in meaning from B?", "answer": False},
        {"question": "Is A a completely different concept from B?", "answer": False},
        {"question": "Is A never used in place of B?", "answer": False},
        {"question": "Do A and B belong to unrelated topics?", "answer": False},
        {"question": "Is A in no way similar to B?", "answer": False},
        {"question": "Does A avoid expressing the idea B expresses?", "answer": False},
        {"question": "Can A and B never appear in similar contexts?", "answer": False},
        {"question": "Would people avoid substituting A for B?", "answer": False},
        {"question": "Do A and B have conflicting definitions?", "answer": False},
        {"question": "Is A less meaningful than B?", "answer": False},
        {"question": "Does A define something totally different from B?", "answer": False},
        {"question": "Are A and B different parts of speech always?", "answer": False},
        {"question": "Does A exclude the meaning of B?", "answer": False},
        {"question": "Is A a hypernym of B?", "answer": False},
        {"question": "Is B a synonym only by mistake?", "answer": False},
        {"question": "Is A a slang word while B is not related?", "answer": False},
        {"question": "Is A a misspelling of B rather than a synonym?", "answer": False},
        {"question": "Do A and B refer to completely unconnected things?", "answer": False},
        {"question": "Would A and B never be matched in a thesaurus?", "answer": False},
        {"question": "Do A and B exclude each other logically?", "answer": False},
        {"question": "Is A always used in a different context from B?", "answer": False},
        {"question": "Do A and B refer to opposite categories?", "answer": False},
        {"question": "Does A contradict the usage of B?", "answer": False},
        {"question": "Can A never replace B in a sentence?", "answer": False},
        {"question": "Is A a translation of B rather than a synonym?", "answer": False},
        {"question": "Does A imply the opposite of B?", "answer": False},
        {"question": "Are A and B incompatible in meaning?", "answer": False},
        {"question": "Would it be incorrect to claim A is a synonym of B?", "answer": False},
        {"question": "Are A and B semantically distant?", "answer": False},
        {"question": "Does A fail to capture any meaning from B?", "answer": False},
        {"question": "Is there no semantic overlap between A and B?", "answer": False},
        {"question": "Do A and B always contradict each other?", "answer": False},
        {"question": "Does A express a meaning unrelated to B?", "answer": False},
        {"question": "Is A not equivalent in any sense to B?", "answer": False},
        {"question": "Would a dictionary mark A and B as unrelated?", "answer": False},
        {"question": "Is A too specific compared to B to be a synonym?", "answer": False},
        {"question": "Is B a broader category rather than a synonym of A?", "answer": False},
        {"question": "Does A misrepresent the meaning of B?", "answer": False},
        {"question": "Is A often confused with B but actually different?", "answer": False},
        {"question": "Do A and B belong to opposite semantic groups?", "answer": False}
    ],
    "CapableOf": [
        {"question": "Is A capable of B?", "answer": True},
        {"question": "Can A perform B?", "answer": True},
        {"question": "Is A able to do B?", "answer": True},
        {"question": "Does A have the ability to B?", "answer": True},
        {"question": "Can A achieve B?", "answer": True},
        {"question": "Is A naturally capable of B?", "answer": True},
        {"question": "Is A known to do B?", "answer": True},
        {"question": "Can A successfully carry out B?", "answer": True},
        {"question": "Is A often used to B?", "answer": True},
        {"question": "Is A designed to do B?", "answer": True},
        {"question": "Can A be used to perform B?", "answer": True},
        {"question": "Is B an ability of A?", "answer": True},
        {"question": "Is A sometimes used to achieve B?", "answer": True},
        {"question": "Is A capable of performing B under normal conditions?", "answer": True},
        {"question": "Is A able to accomplish B?", "answer": True},
        {"question": "Does A have the capability for B?", "answer": True},
        {"question": "Is B an action that A can do?", "answer": True},
        {"question": "Can A engage in B?", "answer": True},
        {"question": "Is A frequently capable of B?", "answer": True},
        {"question": "Is A suitable for performing B?", "answer": True},
        {"question": "Is A incapable of B?", "answer": False},
        {"question": "Does A lack the ability to B?", "answer": False},
        {"question": "Is A unable to perform B?", "answer": False},
        {"question": "Is A never able to do B?", "answer": False},
        {"question": "Does A fail to do B?", "answer": False},
        {"question": "Is A not designed for B?", "answer": False},
        {"question": "Can A not be used to perform B?", "answer": False},
        {"question": "Is B impossible for A to do?", "answer": False},
        {"question": "Is A useless for performing B?", "answer": False},
        {"question": "Is A incapable by nature of doing B?", "answer": False},
        {"question": "Is A prevented from doing B?", "answer": False},
        {"question": "Does A completely lack the capability for B?", "answer": False},
        {"question": "Is A unable to achieve B in any context?", "answer": False},
        {"question": "Is A not suited to perform B?", "answer": False},
        {"question": "Is B beyond A's abilities?", "answer": False},
        {"question": "Is it false that A can do B?", "answer": False},
        {"question": "Is A unqualified to perform B?", "answer": False},
        {"question": "Would A fail to perform B?", "answer": False},
        {"question": "Is B something A can never do?", "answer": False},
        {"question": "Does A have no ability to accomplish B?", "answer": False},
        {"question": "Is B unrelated to A's abilities?", "answer": False},
        {"question": "Is A completely incapable of performing B?", "answer": False},
        {"question": "Is A unable to engage in B?", "answer": False},
        {"question": "Is A never used to do B?", "answer": False},
        {"question": "Does A lack the necessary features to do B?", "answer": False},
        {"question": "Is A too weak to perform B?", "answer": False},
        {"question": "Is A not functional enough to do B?", "answer": False},
        {"question": "Is A unable to execute B?", "answer": False},
        {"question": "Does A not possess the required properties to do B?", "answer": False},
        {"question": "Is A unfit to perform B?", "answer": False},
        {"question": "Is A incapable even in ideal conditions of doing B?", "answer": False},
        {"question": "Would A never be considered able to do B?", "answer": False},
        {"question": "Is A not capable of handling B?", "answer": False},
        {"question": "Is B impossible for A by definition?", "answer": False},
        {"question": "Does A never show any ability to do B?", "answer": False},
        {"question": "Is A known to fail at performing B?", "answer": False},
        {"question": "Does A lack the potential to do B?", "answer": False},
        {"question": "Is B outside the scope of A's abilities?", "answer": False},
        {"question": "Is A unable to perform B effectively?", "answer": False},
        {"question": "Would A be incapable of B even with help?", "answer": False},
        {"question": "Is B not something A can perform?", "answer": False},
        {"question": "Is A unprepared to perform B?", "answer": False},
        {"question": "Does A show no ability to accomplish B?", "answer": False},
        {"question": "Is A powerless to do B?", "answer": False},
        {"question": "Is A functionally unable to do B?", "answer": False},
        {"question": "Can A not carry out B?", "answer": False},
        {"question": "Is B not among A's capabilities?", "answer": False},
        {"question": "Would A always fail at B?", "answer": False},
        {"question": "Is A completely unfit for B?", "answer": False},
        {"question": "Is A inherently unable to perform B?", "answer": False}
    ],
    "AtLocation": [
        {"question": "Is A typically found at B?", "answer": True},
        {"question": "Can A be located at B?", "answer": True},
        {"question": "Is B a common place to find A?", "answer": True},
        {"question": "Would you expect to see A at B?", "answer": True},
        {"question": "Is A often present at B?", "answer": True},
        {"question": "Might A be found at B?", "answer": True},
        {"question": "Is B a usual location for A?", "answer": True},
        {"question": "Is A commonly seen at B?", "answer": True},
        {"question": "Could A be found at B under normal circumstances?", "answer": True},
        {"question": "Is B a possible location for A?", "answer": True},
        {"question": "Is A usually located at B?", "answer": True},
        {"question": "Is B one of the places where A exists?", "answer": True},
        {"question": "Is A generally found at B?", "answer": True},
        {"question": "Would A be found at B frequently?", "answer": True},
        {"question": "Is B known to contain A?", "answer": True},
        {"question": "Is A stored at B?", "answer": True},
        {"question": "Is B a habitat for A?", "answer": True},
        {"question": "Is A situated at B?", "answer": True},
        {"question": "Is B a location associated with A?", "answer": True},
        {"question": "Can A exist at B?", "answer": True},
        {"question": "Is A never found at B?", "answer": False},
        {"question": "Is B an impossible location for A?", "answer": False},
        {"question": "Would you never see A at B?", "answer": False},
        {"question": "Is A unrelated to location B?", "answer": False},
        {"question": "Is A always absent from B?", "answer": False},
        {"question": "Can A not be located at B?", "answer": False},
        {"question": "Is B not a place where A can be?", "answer": False},
        {"question": "Is A never present at B?", "answer": False},
        {"question": "Is it false that A can be found at B?", "answer": False},
        {"question": "Is A impossible to find at B?", "answer": False},
        {"question": "Would A never exist at B?", "answer": False},
        {"question": "Is B not a possible place for A?", "answer": False},
        {"question": "Is A not typically present at B?", "answer": False},
        {"question": "Is B completely unrelated to A?", "answer": False},
        {"question": "Is A always outside B?", "answer": False},
        {"question": "Is A excluded from being at B?", "answer": False},
        {"question": "Is B never associated with A?", "answer": False},
        {"question": "Would A definitely not be found at B?", "answer": False},
        {"question": "Is B not known to contain A?", "answer": False},
        {"question": "Does A never appear at B?", "answer": False},
        {"question": "Is A far from location B?", "answer": False},
        {"question": "Is A not allowed to be at B?", "answer": False},
        {"question": "Is there no chance to find A at B?", "answer": False},
        {"question": "Is A completely absent from B?", "answer": False},
        {"question": "Is A not commonly found at B?", "answer": False},
        {"question": "Is it unreasonable to find A at B?", "answer": False},
        {"question": "Would it be false to say A is at B?", "answer": False},
        {"question": "Is A unable to be located at B?", "answer": False},
        {"question": "Is B not a location where A would appear?", "answer": False},
        {"question": "Is A never seen at place B?", "answer": False},
        {"question": "Is A rarely if ever located at B?", "answer": False},
        {"question": "Does A avoid location B?", "answer": False},
        {"question": "Is B not associated with A at all?", "answer": False},
        {"question": "Is A not normally present at B?", "answer": False},
        {"question": "Is B irrelevant to finding A?", "answer": False},
        {"question": "Is A unable to exist at B?", "answer": False},
        {"question": "Is A out of place at B?", "answer": False},
        {"question": "Is A never stored at B?", "answer": False},
        {"question": "Would B never have A?", "answer": False},
        {"question": "Is A not found within B?", "answer": False},
        {"question": "Is B not a known place for A?", "answer": False},
        {"question": "Does A never stay at B?", "answer": False},
        {"question": "Is A definitely not at B?", "answer": False},
        {"question": "Is A always far from B?", "answer": False},
        {"question": "Is there no situation where A could be at B?", "answer": False},
        {"question": "Is A forbidden from being at B?", "answer": False},
        {"question": "Is A always located away from B?", "answer": False},
        {"question": "Can A never appear in B?", "answer": False},
        {"question": "Is it impossible for A to be found in B?", "answer": False}
    ],
    "HasProperty": [
        {"question": "Does A have the property B?", "answer": True},
        {"question": "Is A characterized by B?", "answer": True},
        {"question": "Is B a feature of A?", "answer": True},
        {"question": "Can A be described as B?", "answer": True},
        {"question": "Is B one of A's properties?", "answer": True},
        {"question": "Is A known for being B?", "answer": True},
        {"question": "Would you say A is B?", "answer": True},
        {"question": "Is A generally considered B?", "answer": True},
        {"question": "Is B true about A?", "answer": True},
        {"question": "Can A be seen as B?", "answer": True},
        {"question": "Is it correct that A is B?", "answer": True},
        {"question": "Is B accurate about A?", "answer": True},
        {"question": "Does A typically show property B?", "answer": True},
        {"question": "Is A usually B?", "answer": True},
        {"question": "Is B associated with A?", "answer": True},
        {"question": "Is A often described as B?", "answer": True},
        {"question": "Is A naturally B?", "answer": True},
        {"question": "Is A normally B?", "answer": True},
        {"question": "Would B describe A?", "answer": True},
        {"question": "Can B be used to define A?", "answer": True},
        {"question": "Does A lack property B?", "answer": False},
        {"question": "Is it false that A is B?", "answer": False},
        {"question": "Is B not a property of A?", "answer": False},
        {"question": "Is A never B?", "answer": False},
        {"question": "Is A rarely B?", "answer": False},
        {"question": "Is A not known to be B?", "answer": False},
        {"question": "Is B inaccurate about A?", "answer": False},
        {"question": "Is A the opposite of B?", "answer": False},
        {"question": "Is A unrelated to B?", "answer": False},
        {"question": "Is A not described as B?", "answer": False},
        {"question": "Is B never true for A?", "answer": False},
        {"question": "Is A not associated with B?", "answer": False},
        {"question": "Is A definitely not B?", "answer": False},
        {"question": "Is A seldom considered B?", "answer": False},
        {"question": "Is A far from being B?", "answer": False},
        {"question": "Is A not typically B?", "answer": False},
        {"question": "Is B not accurate about A?", "answer": False},
        {"question": "Is B not used to describe A?", "answer": False},
        {"question": "Is A not naturally B?", "answer": False},
        {"question": "Is A not characterized by B?", "answer": False},
        {"question": "Would you say A is not B?", "answer": False},
        {"question": "Is B never a feature of A?", "answer": False},
        {"question": "Is B not true about A?", "answer": False},
        {"question": "Can A not be described as B?", "answer": False},
        {"question": "Is it incorrect to say A is B?", "answer": False},
        {"question": "Is A not generally considered B?", "answer": False},
        {"question": "Is A hardly ever B?", "answer": False},
        {"question": "Is it untrue that A has property B?", "answer": False},
        {"question": "Is A not known for being B?", "answer": False},
        {"question": "Does A never show property B?", "answer": False},
        {"question": "Is A not typically described as B?", "answer": False},
        {"question": "Is B not one of A's properties?", "answer": False},
        {"question": "Is it false that B applies to A?", "answer": False},
        {"question": "Is A not usually B?", "answer": False},
        {"question": "Is it wrong to describe A as B?", "answer": False},
        {"question": "Is A not often B?", "answer": False},
        {"question": "Is A not associated with being B?", "answer": False},
        {"question": "Is A not defined by B?", "answer": False},
        {"question": "Is A not linked to property B?", "answer": False},
        {"question": "Is A never described as B?", "answer": False},
        {"question": "Is A not naturally described as B?", "answer": False},
        {"question": "Is property B never found in A?", "answer": False},
        {"question": "Is A not believed to be B?", "answer": False},
        {"question": "Is A not recognized as B?", "answer": False},
        {"question": "Is A mostly not B?", "answer": False},
        {"question": "Is A not really B?", "answer": False},
        {"question": "Is A not typically thought of as B?", "answer": False},
        {"question": "Is A not properly described as B?", "answer": False},
        {"question": "Is it a mistake to say A is B?", "answer": False},
        {"question": "Is A never thought of as B?", "answer": False},
        {"question": "Is B never used about A?", "answer": False},
        {"question": "Is A totally not B?", "answer": False}
    ],
    "PartOf": [
        {"question": "Is A a part of B?", "answer": True},
        {"question": "Is A included within B?", "answer": True},
        {"question": "Does A belong to the components of B?", "answer": True},
        {"question": "Is A one of the parts that make up B?", "answer": True},
        {"question": "Is A contained inside B?", "answer": True},
        {"question": "Would you say A forms part of B?", "answer": True},
        {"question": "Does B consist partly of A?", "answer": True},
        {"question": "Is A physically connected to B as a component?", "answer": True},
        {"question": "Can A be found as a piece of B?", "answer": True},
        {"question": "Is A structurally part of B?", "answer": True},
        {"question": "Is A a smaller section within B?", "answer": True},
        {"question": "Does B include A as a section?", "answer": True},
        {"question": "Is A one element in the structure of B?", "answer": True},
        {"question": "Does A serve as a portion of B?", "answer": True},
        {"question": "Is A inside B as a necessary component?", "answer": True},
        {"question": "Is A one of the integral parts of B?", "answer": True},
        {"question": "Does A fit as one piece of B?", "answer": True},
        {"question": "Is A found within the boundary of B?", "answer": True},
        {"question": "Is A attached to B as part of its makeup?", "answer": True},
        {"question": "Does B depend partly on A?", "answer": True},
        {"question": "Is A not part of B?", "answer": False},
        {"question": "Is A completely independent from B's structure?", "answer": False},
        {"question": "Can B exist without containing A?", "answer": False},
        {"question": "Is A unrelated to the structure of B?", "answer": False},
        {"question": "Is A never found inside B?", "answer": False},
        {"question": "Is A larger than B and contains it?", "answer": False},
        {"question": "Does B form a part of A?", "answer": False},
        {"question": "Is A the whole of B?", "answer": False},
        {"question": "Is A something separate and not included in B?", "answer": False},
        {"question": "Does A have no connection to B?", "answer": False},
        {"question": "Is A an unrelated object outside of B?", "answer": False},
        {"question": "Does A describe the function of B?", "answer": False},
        {"question": "Is A identical to B in every way?", "answer": False},
        {"question": "Is A a synonym of B rather than a component?", "answer": False},
        {"question": "Does B completely exclude A?", "answer": False},
        {"question": "Is A a category rather than a part of B?", "answer": False},
        {"question": "Is A only associated with B conceptually, not physically?", "answer": False},
        {"question": "Is A made up of B?", "answer": False},
        {"question": "Does A describe something opposite to B?", "answer": False},
        {"question": "Is A a location of B rather than a part?", "answer": False},
        {"question": "Is A used to store B but not part of it?", "answer": False},
        {"question": "Is A something B uses but does not contain?", "answer": False},
        {"question": "Does A exist outside of B entirely?", "answer": False},
        {"question": "Is A not related to B in any meaningful way?", "answer": False},
        {"question": "Is A a separate whole object from B?", "answer": False},
        {"question": "Is A not physically or logically contained in B?", "answer": False},
        {"question": "Is A an action instead of a component of B?", "answer": False},
        {"question": "Does A have no role in forming B?", "answer": False},
        {"question": "Is A totally external to B?", "answer": False},
        {"question": "Is A not inside or connected to B?", "answer": False}
    ],
    "UsedFor": [
        {"question": "Is A used for B?", "answer": True},
        {"question": "Is A commonly used to perform B?", "answer": True},
        {"question": "Can A help achieve B?", "answer": True},
        {"question": "Do people use A for B?", "answer": True},
        {"question": "Is A an effective tool for B?", "answer": True},
        {"question": "Is A useful for B?", "answer": True},
        {"question": "Would someone use A to do B?", "answer": True},
        {"question": "Is A designed to support B?", "answer": True},
        {"question": "Is A meant for doing B?", "answer": True},
        {"question": "Can A assist in B?", "answer": True},
        {"question": "Is A used as a way to do B?", "answer": True},
        {"question": "Is A a common method for B?", "answer": True},
        {"question": "Is A used as a tool in B?", "answer": True},
        {"question": "Could A be used in situations involving B?", "answer": True},
        {"question": "Is A applicable to tasks of doing B?", "answer": True},
        {"question": "Is A suitable for B?", "answer": True},
        {"question": "Might someone use A when performing B?", "answer": True},
        {"question": "Is A involved in the process of B?", "answer": True},
        {"question": "Is A useful when doing B?", "answer": True},
        {"question": "Would A normally be used to carry out B?", "answer": True},
        {"question": "Is A never used for B?", "answer": False},
        {"question": "Is A completely unrelated to B?", "answer": False},
        {"question": "Is A used to do the opposite of B?", "answer": False},
        {"question": "Does A prevent B rather than enable it?", "answer": False},
        {"question": "Is A harmful for doing B?", "answer": False},
        {"question": "Is A used for C instead of B?", "answer": False},
        {"question": "Is A incapable of being used for B?", "answer": False},
        {"question": "Is A not designed or intended for B?", "answer": False},
        {"question": "Is A unrelated to any process involving B?", "answer": False},
        {"question": "Do people avoid using A for B?", "answer": False},
        {"question": "Is A the result of B rather than used for it?", "answer": False},
        {"question": "Is A a location where B happens, not used for it?", "answer": False},
        {"question": "Is A a part of B rather than used for it?", "answer": False},
        {"question": "Is A a type of B, not used for B?", "answer": False},
        {"question": "Is A a person who does B rather than used for it?", "answer": False},
        {"question": "Is A a concept rather than a tool for B?", "answer": False},
        {"question": "Is A too weak to be used for B?", "answer": False},
        {"question": "Is A too large to use for B?", "answer": False},
        {"question": "Is A only used in a way opposite to B?", "answer": False},
        {"question": "Is A only decorative and not used for B?", "answer": False},
        {"question": "Is A a name and not used for B?", "answer": False},
        {"question": "Is A completely useless for B?", "answer": False},
        {"question": "Is A used only for entertainment and not for B?", "answer": False},
        {"question": "Is A a food item, not used for B?", "answer": False},
        {"question": "Is A only a measurement of B, not used for it?", "answer": False},
        {"question": "Is A a place where B happens but not used for B?", "answer": False},
        {"question": "Is A a disease and not used for B?", "answer": False},
        {"question": "Is A made by B instead of used for B?", "answer": False},
        {"question": "Is A the purpose of B instead of used for B?", "answer": False},
        {"question": "Is A only observed in B but not used for it?", "answer": False}
    ],
    "CausesDesire": [
        {"question": "Does A cause a desire for B?", "answer": True},
        {"question": "Can experiencing A make someone want B?", "answer": True},
        {"question": "Does A often lead people to want B?", "answer": True},
        {"question": "Is A something that makes people feel like doing B?", "answer": True},
        {"question": "Does A trigger a desire to B?", "answer": True},
        {"question": "Can A motivate someone to want B?", "answer": True},
        {"question": "Is A likely to cause someone to seek B?", "answer": True},
        {"question": "Does A make people think about doing B?", "answer": True},
        {"question": "Is A known to create a desire for B?", "answer": True},
        {"question": "Can A inspire a person to pursue B?", "answer": True},
        {"question": "Does A encourage people to want B?", "answer": True},
        {"question": "Does A naturally make people more interested in B?", "answer": True},
        {"question": "Can A emotionally lead to a desire for B?", "answer": True},
        {"question": "Is A associated with wanting B afterward?", "answer": True},
        {"question": "Is A something that drives a person toward B?", "answer": True},
        {"question": "Does A result in people wanting B?", "answer": True},
        {"question": "Is A a cause of craving for B?", "answer": True},
        {"question": "Can A awaken an urge to do B?", "answer": True},
        {"question": "Is A likely to make B seem desirable?", "answer": True},
        {"question": "Does A lead to a wish for B?", "answer": True},
        {"question": "Does A prevent any desire for B?", "answer": False},
        {"question": "Does A make people hate the idea of B?", "answer": False},
        {"question": "Does A reduce interest in B instead of causing it?", "answer": False},
        {"question": "Does A make people avoid B?", "answer": False},
        {"question": "Is A unrelated to wanting B?", "answer": False},
        {"question": "Does A stop people from feeling like doing B?", "answer": False},
        {"question": "Does A cause the opposite of wanting B?", "answer": False},
        {"question": "Does A discourage any thoughts of B?", "answer": False},
        {"question": "Does A make B unnecessary rather than desired?", "answer": False},
        {"question": "Does A destroy any motivation for B?", "answer": False},
        {"question": "Does A cause fear instead of desire for B?", "answer": False},
        {"question": "Does A lead to anger instead of a desire for B?", "answer": False},
        {"question": "Is A only a tool used to get B, not cause desire for it?", "answer": False},
        {"question": "Is A the result of wanting B, not the cause?", "answer": False},
        {"question": "Does A eliminate the need for B?", "answer": False},
        {"question": "Does A replace B rather than make someone desire it?", "answer": False},
        {"question": "Is A completely unrelated to motivation for B?", "answer": False},
        {"question": "Does A block any emotional desire for B?", "answer": False},
        {"question": "Does A happen after B, not before?", "answer": False},
        {"question": "Does A make people forget about B entirely?", "answer": False},
        {"question": "Does A have nothing to do with feelings at all?", "answer": False},
        {"question": "Is A purely physical and not emotional like desire for B?", "answer": False},
        {"question": "Does A cause confusion instead of desire for B?", "answer": False},
        {"question": "Does A cause pain instead of desire for B?", "answer": False},
        {"question": "Does A only relate to survival and not desire for B?", "answer": False},
        {"question": "Does A directly stop B from happening?", "answer": False},
        {"question": "Does A satisfy B rather than cause want for it?", "answer": False},
        {"question": "Is A unconnected to thoughts of doing B?", "answer": False},
        {"question": "Does A prevent people from thinking about B?", "answer": False},
        {"question": "Does A lead to boredom instead of desire for B?", "answer": False},
        {"question": "Does A satisfy the desire for B instead of causing it?", "answer": False}
    ],
    "ReceivesAction": [
        {"question": "Does A receive the action B?", "answer": True},
        {"question": "Is A affected by B?", "answer": True},
        {"question": "Can B be performed on A?", "answer": True},
        {"question": "Is A the recipient of B?", "answer": True},
        {"question": "Does B happen to A?", "answer": True},
        {"question": "Is A acted upon by B?", "answer": True},
        {"question": "Can B be done to A?", "answer": True},
        {"question": "Is A influenced by B?", "answer": True},
        {"question": "Does A experience B?", "answer": True},
        {"question": "Is A subjected to B?", "answer": True},
        {"question": "Is A affected when B occurs?", "answer": True},
        {"question": "Does B impact A?", "answer": True},
        {"question": "Is A a target of B?", "answer": True},
        {"question": "Can A undergo B?", "answer": True},
        {"question": "Does A get B done to it?", "answer": True},
        {"question": "Is B applied to A?", "answer": True},
        {"question": "Is A a recipient of B's action?", "answer": True},
        {"question": "Does A come under B?", "answer": True},
        {"question": "Is A influenced or changed by B?", "answer": True},
        {"question": "Does A experience the effect of B?", "answer": True},
        {"question": "Does A not receive B?", "answer": False},
        {"question": "Is A unaffected by B?", "answer": False},
        {"question": "Can B not be performed on A?", "answer": False},
        {"question": "Is A never the recipient of B?", "answer": False},
        {"question": "Does B not happen to A?", "answer": False},
        {"question": "Is A free from the action B?", "answer": False},
        {"question": "Does A avoid B?", "answer": False},
        {"question": "Is A completely independent of B?", "answer": False},
        {"question": "Does B have no effect on A?", "answer": False},
        {"question": "Is A not subjected to B?", "answer": False},
        {"question": "Is A not acted upon by B?", "answer": False},
        {"question": "Does A remain unaffected by B?", "answer": False},
        {"question": "Is A untouched by B?", "answer": False},
        {"question": "Does B not influence A?", "answer": False},
        {"question": "Is A never impacted by B?", "answer": False},
        {"question": "Does A not undergo B?", "answer": False},
        {"question": "Is B never applied to A?", "answer": False},
        {"question": "Is A outside the effect of B?", "answer": False},
        {"question": "Does A not come under B?", "answer": False},
        {"question": "Is A unaffected or unchanged by B?", "answer": False},
        {"question": "Does A escape the influence of B?", "answer": False},
        {"question": "Is A completely unaffected by B?", "answer": False},
        {"question": "Is A immune to B?", "answer": False},
        {"question": "Does B bypass A?", "answer": False},
        {"question": "Is A not targeted by B?", "answer": False},
        {"question": "Does A not experience B?", "answer": False},
        {"question": "Is A outside the scope of B?", "answer": False},
        {"question": "Is B irrelevant to A?", "answer": False},
        {"question": "Is A safe from B?", "answer": False},
        {"question": "Does A avoid being affected by B?", "answer": False},
        {"question": "Is A outside B's effect?", "answer": False},
        {"question": "Is A not changed by B?", "answer": False},
        {"question": "Does B not touch A?", "answer": False},
        {"question": "Is A independent of the action B?", "answer": False},
        {"question": "Is A outside of the influence of B?", "answer": False},
        {"question": "Does A not react to B?", "answer": False},
        {"question": "Is A exempt from B?", "answer": False},
        {"question": "Does A avoid receiving B?", "answer": False},
        {"question": "Is B never directed at A?", "answer": False},
        {"question": "Is A not affected or changed by B?", "answer": False},
        {"question": "Does A not undergo any part of B?", "answer": False},
        {"question": "Is A untouched or unaffected by B?", "answer": False},
        {"question": "Is A always outside B?", "answer": False},
        {"question": "Does B have no influence on A?", "answer": False},
        {"question": "Is A unaffected when B occurs?", "answer": False},
        {"question": "Is A outside B’s reach?", "answer": False},
        {"question": "Is B incapable of acting on A?", "answer": False},
        {"question": "Is A completely separate from B?", "answer": False},
        {"question": "Does A not undergo any effect from B?", "answer": False}
    ],
    "Antonym": [
        {"question": "Is A the opposite of B?", "answer": True},
        {"question": "Does A have a meaning contrary to B?", "answer": True},
        {"question": "Is A different from B in the opposite sense?", "answer": True},
        {"question": "Can A be considered the antonym of B?", "answer": True},
        {"question": "Is A conceptually opposite to B?", "answer": True},
        {"question": "Is A the reverse of B?", "answer": True},
        {"question": "Would you say A contradicts B?", "answer": True},
        {"question": "Is A logically opposed to B?", "answer": True},
        {"question": "Is A the negation of B?", "answer": True},
        {"question": "Does A mean the opposite of B?", "answer": True},
        {"question": "Is A an antonym of B?", "answer": True},
        {"question": "Is A the contrary of B?", "answer": True},
        {"question": "Is A the reverse meaning of B?", "answer": True},
        {"question": "Is A the semantic opposite of B?", "answer": True},
        {"question": "Does A convey the opposite sense of B?", "answer": True},
        {"question": "Is A the negated form of B?", "answer": True},
        {"question": "Is A conceptually contrary to B?", "answer": True},
        {"question": "Can A be used as the antonym of B?", "answer": True},
        {"question": "Is A understood as opposite to B?", "answer": True},
        {"question": "Is A contrasted with B?", "answer": True},
        {"question": "Is A the same as B?", "answer": False},
        {"question": "Does A have a meaning similar to B?", "answer": False},
        {"question": "Is A related to B in a similar sense?", "answer": False},
        {"question": "Can A be considered a synonym of B?", "answer": False},
        {"question": "Is A conceptually identical to B?", "answer": False},
        {"question": "Is A aligned with B rather than opposite?", "answer": False},
        {"question": "Would you say A matches B?", "answer": False},
        {"question": "Is A logically equivalent to B?", "answer": False},
        {"question": "Is A not contrary to B?", "answer": False},
        {"question": "Does A convey the same sense as B?", "answer": False},
        {"question": "Is A a synonym of B?", "answer": False},
        {"question": "Is A the same meaning as B?", "answer": False},
        {"question": "Is A similar to B in meaning?", "answer": False},
        {"question": "Does A agree with the sense of B?", "answer": False},
        {"question": "Is A the same concept as B?", "answer": False},
        {"question": "Is A not the opposite of B?", "answer": False},
        {"question": "Is A identical to B?", "answer": False},
        {"question": "Can A be used as a synonym for B?", "answer": False},
        {"question": "Is A equivalent to B?", "answer": False},
        {"question": "Is A aligned with B in meaning?", "answer": False},
        {"question": "Is A similar rather than opposite to B?", "answer": False},
        {"question": "Is A related to B but not as an antonym?", "answer": False},
        {"question": "Does A share the same meaning as B?", "answer": False},
        {"question": "Is A consistent with B?", "answer": False},
        {"question": "Is A complementary rather than opposite to B?", "answer": False},
        {"question": "Is A in agreement with B?", "answer": False},
        {"question": "Is A matching B in meaning?", "answer": False},
        {"question": "Is A not opposed to B?", "answer": False},
        {"question": "Is A a synonym instead of antonym for B?", "answer": False},
        {"question": "Is A similar in concept to B?", "answer": False},
        {"question": "Is A aligned with the meaning of B?", "answer": False},
        {"question": "Is A not contrary to B in meaning?", "answer": False},
        {"question": "Is A compatible with B?", "answer": False},
        {"question": "Is A harmonious with B?", "answer": False},
        {"question": "Does A agree with the concept of B?", "answer": False},
        {"question": "Is A reinforcing rather than opposing B?", "answer": False},
        {"question": "Is A the same in definition as B?", "answer": False},
        {"question": "Is A supporting B instead of contradicting?", "answer": False},
        {"question": "Is A not the negation of B?", "answer": False},
        {"question": "Is A related to B but not as opposite?", "answer": False},
        {"question": "Does A share properties with B rather than oppose it?", "answer": False},
        {"question": "Is A in line with B?", "answer": False},
        {"question": "Is A in harmony with B?", "answer": False},
        {"question": "Is A comparable to B rather than opposite?", "answer": False},
        {"question": "Is A not the contrary of B?", "answer": False},
        {"question": "Is A not the inverse of B?", "answer": False},
        {"question": "Is A similar to B rather than contradictory?", "answer": False},
        {"question": "Is A consistent with B instead of opposing?", "answer": False}
    ],
    "DefinedAs": [
        {"question": "Is A defined as B?", "answer": True},
        {"question": "Does A mean B?", "answer": True},
        {"question": "Is B the definition of A?", "answer": True},
        {"question": "Can A be described as B?", "answer": True},
        {"question": "Is A explained by B?", "answer": True},
        {"question": "Is A referred to as B?", "answer": True},
        {"question": "Is B what A represents?", "answer": True},
        {"question": "Does B describe A?", "answer": True},
        {"question": "Is A characterized as B?", "answer": True},
        {"question": "Is A equivalent to the concept B?", "answer": True},
        {"question": "Is B an accurate definition of A?", "answer": True},
        {"question": "Is A synonymous with the description B?", "answer": True},
        {"question": "Can A be summarized as B?", "answer": True},
        {"question": "Is B used to define A?", "answer": True},
        {"question": "Does B explain the meaning of A?", "answer": True},
        {"question": "Is A expressed as B?", "answer": True},
        {"question": "Is B the correct interpretation of A?", "answer": True},
        {"question": "Does A correspond to B?", "answer": True},
        {"question": "Is B the exact definition of A?", "answer": True},
        {"question": "Can A be described by B?", "answer": True},
        {"question": "Is A not defined as B?", "answer": False},
        {"question": "Does A mean something other than B?", "answer": False},
        {"question": "Is B unrelated to defining A?", "answer": False},
        {"question": "Is A described differently than B?", "answer": False},
        {"question": "Is A not explained by B?", "answer": False},
        {"question": "Is A something else other than B?", "answer": False},
        {"question": "Does B fail to describe A?", "answer": False},
        {"question": "Is A incorrectly defined as B?", "answer": False},
        {"question": "Is A not synonymous with B?", "answer": False},
        {"question": "Does A correspond to C instead of B?", "answer": False},
        {"question": "Is B irrelevant to the meaning of A?", "answer": False},
        {"question": "Is A expressed differently from B?", "answer": False},
        {"question": "Does B not explain A?", "answer": False},
        {"question": "Is A unrelated to the description B?", "answer": False},
        {"question": "Is A characterized by something other than B?", "answer": False},
        {"question": "Is B not an accurate definition of A?", "answer": False},
        {"question": "Is A expressed incorrectly as B?", "answer": False},
        {"question": "Does A represent something other than B?", "answer": False},
        {"question": "Is B not what A stands for?", "answer": False},
        {"question": "Is A not defined by B?", "answer": False},
        {"question": "Does A contradict the definition B?", "answer": False},
        {"question": "Is A different in meaning than B?", "answer": False},
        {"question": "Is B an unrelated concept to A?", "answer": False},
        {"question": "Is A a different thing than B?", "answer": False},
        {"question": "Does B misrepresent A?", "answer": False},
        {"question": "Is A not equivalent to B?", "answer": False},
        {"question": "Is B not the explanation of A?", "answer": False},
        {"question": "Does A have a meaning other than B?", "answer": False},
        {"question": "Is A misdescribed as B?", "answer": False},
        {"question": "Is A something else entirely?", "answer": False},
        {"question": "Is B unrelated to the concept of A?", "answer": False},
        {"question": "Is A incorrectly represented by B?", "answer": False},
        {"question": "Is A not expressed as B?", "answer": False},
        {"question": "Does B fail to define A?", "answer": False},
        {"question": "Is A described by C instead of B?", "answer": False},
        {"question": "Is A unrelated to the description B?", "answer": False},
        {"question": "Is B not representative of A?", "answer": False},
        {"question": "Is A not summarized by B?", "answer": False},
        {"question": "Is A defined incorrectly as B?", "answer": False},
        {"question": "Is A something different than B?", "answer": False},
        {"question": "Does B not correspond to A?", "answer": False},
        {"question": "Is A described incorrectly?", "answer": False},
        {"question": "Is B irrelevant to describing A?", "answer": False},
        {"question": "Is A not explained by B?", "answer": False},
        {"question": "Is A misrepresented by B?", "answer": False},
        {"question": "Does A mean anything other than B?", "answer": False},
        {"question": "Is B not related to defining A?", "answer": False}
    ],
    "SimilarTo": [
        {"question": "Is A similar to B?", "answer": True},
        {"question": "Does A resemble B?", "answer": True},
        {"question": "Is A comparable to B?", "answer": True},
        {"question": "Can A be seen as like B?", "answer": True},
        {"question": "Is A akin to B?", "answer": True},
        {"question": "Does A share features with B?", "answer": True},
        {"question": "Is A analogous to B?", "answer": True},
        {"question": "Does A have characteristics like B?", "answer": True},
        {"question": "Is A in the same category as B?", "answer": True},
        {"question": "Is A comparable in nature to B?", "answer": True},
        {"question": "Is A closely related to B?", "answer": True},
        {"question": "Does A look like B in some way?", "answer": True},
        {"question": "Is A resembling B?", "answer": True},
        {"question": "Is A like B in certain aspects?", "answer": True},
        {"question": "Does A share similarities with B?", "answer": True},
        {"question": "Is A related to B in a similar manner?", "answer": True},
        {"question": "Is A comparable with B?", "answer": True},
        {"question": "Is A akin in meaning to B?", "answer": True},
        {"question": "Does A have a likeness to B?", "answer": True},
        {"question": "Is A like B?", "answer": True},
        {"question": "Is A not similar to B?", "answer": False},
        {"question": "Does A differ from B?", "answer": False},
        {"question": "Is A unrelated to B?", "answer": False},
        {"question": "Is A the opposite of B?", "answer": False},
        {"question": "Does A contrast with B?", "answer": False},
        {"question": "Is A distinct from B?", "answer": False},
        {"question": "Is A not like B?", "answer": False},
        {"question": "Is A completely different from B?", "answer": False},
        {"question": "Does A share no features with B?", "answer": False},
        {"question": "Is A unrelated in meaning to B?", "answer": False},
        {"question": "Is A unlike B?", "answer": False},
        {"question": "Does A have nothing in common with B?", "answer": False},
        {"question": "Is A dissimilar to B?", "answer": False},
        {"question": "Is A far from being like B?", "answer": False},
        {"question": "Is A unrelated to B in any aspect?", "answer": False},
        {"question": "Is A completely unlike B?", "answer": False},
        {"question": "Is A opposite in meaning to B?", "answer": False},
        {"question": "Does A not resemble B in any way?", "answer": False},
        {"question": "Is A contrasting with B?", "answer": False},
        {"question": "Is A unrelated to the characteristics of B?", "answer": False},
        {"question": "Is A nothing like B?", "answer": False},
        {"question": "Is A completely unrelated to B?", "answer": False},
        {"question": "Does A have no resemblance to B?", "answer": False},
        {"question": "Is A not comparable to B?", "answer": False},
        {"question": "Is A opposite rather than similar to B?", "answer": False},
        {"question": "Is A lacking similarity to B?", "answer": False},
        {"question": "Is A not akin to B?", "answer": False},
        {"question": "Is A unlike any aspect of B?", "answer": False},
        {"question": "Is A entirely different from B?", "answer": False},
        {"question": "Is A never comparable with B?", "answer": False},
        {"question": "Is A totally dissimilar to B?", "answer": False},
        {"question": "Does A have no analogy to B?", "answer": False},
        {"question": "Is A unrelated to B?", "answer": False},
        {"question": "Is A not akin in any sense to B?", "answer": False},
        {"question": "Is A unlike B entirely?", "answer": False},
        {"question": "Is A nothing like the concept B?", "answer": False},
        {"question": "Does A have no likeness to B?", "answer": False},
        {"question": "Is A opposite or different from B?", "answer": False},
        {"question": "Is A unrelated or different from B?", "answer": False},
        {"question": "Is A unalike B?", "answer": False},
        {"question": "Is A contrasting rather than resembling B?", "answer": False},
        {"question": "Is A unrelated to the idea of B?", "answer": False},
        {"question": "Is A opposite in concept to B?", "answer": False},
        {"question": "Is A unconnected to B?", "answer": False},
        {"question": "Is A nothing like the idea B?", "answer": False},
        {"question": "Is A entirely unalike B?", "answer": False},
        {"question": "Is A dissimilar in all aspects to B?", "answer": False}
    ],
    "HasA": [
        {"question": "Does A have B?", "answer": True},
        {"question": "Is B a part or feature of A?", "answer": True},
        {"question": "Does A possess B?", "answer": True},
        {"question": "Is B contained within A?", "answer": True},
        {"question": "Does A include B?", "answer": True},
        {"question": "Is B an attribute of A?", "answer": True},
        {"question": "Is B something A owns?", "answer": True},
        {"question": "Is B a characteristic of A?", "answer": True},
        {"question": "Does A consist of B?", "answer": True},
        {"question": "Is B associated with A?", "answer": True},
        {"question": "Is B a feature of A?", "answer": True},
        {"question": "Does A contain B?", "answer": True},
        {"question": "Is B part of the makeup of A?", "answer": True},
        {"question": "Is B found in A?", "answer": True},
        {"question": "Does A include the element B?", "answer": True},
        {"question": "Is B a component of A?", "answer": True},
        {"question": "Is B present in A?", "answer": True},
        {"question": "Does A carry B?", "answer": True},
        {"question": "Is B an inherent part of A?", "answer": True},
        {"question": "Is B a property of A?", "answer": True},
        {"question": "Does A not have B?", "answer": False},
        {"question": "Is B absent from A?", "answer": False},
        {"question": "Does A lack B?", "answer": False},
        {"question": "Is B not contained in A?", "answer": False},
        {"question": "Does A exclude B?", "answer": False},
        {"question": "Is B not an attribute of A?", "answer": False},
        {"question": "Is B something A does not own?", "answer": False},
        {"question": "Is B not a characteristic of A?", "answer": False},
        {"question": "Does A not consist of B?", "answer": False},
        {"question": "Is B unrelated to A?", "answer": False},
        {"question": "Is B not a feature of A?", "answer": False},
        {"question": "Does A lack the element B?", "answer": False},
        {"question": "Is B missing from A?", "answer": False},
        {"question": "Is B not part of the makeup of A?", "answer": False},
        {"question": "Does A contain something other than B?", "answer": False},
        {"question": "Is B not a component of A?", "answer": False},
        {"question": "Is B absent within A?", "answer": False},
        {"question": "Does A not carry B?", "answer": False},
        {"question": "Is B not an inherent part of A?", "answer": False},
        {"question": "Is B not a property of A?", "answer": False},
        {"question": "Does A lack any relation to B?", "answer": False},
        {"question": "Is B unrelated to the structure of A?", "answer": False},
        {"question": "Is B not found in A?", "answer": False},
        {"question": "Does A have nothing to do with B?", "answer": False},
        {"question": "Is B absent from A’s features?", "answer": False},
        {"question": "Does A not possess B?", "answer": False},
        {"question": "Is B excluded from A?", "answer": False},
        {"question": "Is B missing in A?", "answer": False},
        {"question": "Does A have another attribute instead of B?", "answer": False},
        {"question": "Is B not part of A at all?", "answer": False},
        {"question": "Does A carry something other than B?", "answer": False},
        {"question": "Is B non-existent in A?", "answer": False},
        {"question": "Is B irrelevant to A?", "answer": False},
        {"question": "Is B not present in A?", "answer": False},
        {"question": "Does A not include B?", "answer": False},
        {"question": "Is B absent from A’s composition?", "answer": False},
        {"question": "Does A contain something different from B?", "answer": False},
        {"question": "Is B not part of the contents of A?", "answer": False},
        {"question": "Does A not feature B?", "answer": False},
        {"question": "Is B not incorporated in A?", "answer": False},
        {"question": "Is B not associated with A?", "answer": False},
        {"question": "Is B missing from A completely?", "answer": False},
        {"question": "Is B not one of A’s elements?", "answer": False},
        {"question": "Is B absent as a part of A?", "answer": False},
        {"question": "Does A not include B as a component?", "answer": False},
        {"question": "Is B not found among A’s features?", "answer": False},
        {"question": "Does A lack the component B?", "answer": False},
        {"question": "Is B entirely missing from A?", "answer": False}
    ],
    "MadeOf": [
        {"question": "Is A made of B?", "answer": True},
        {"question": "Does A consist of B?", "answer": True},
        {"question": "Is B a material that composes A?", "answer": True},
        {"question": "Is A constructed from B?", "answer": True},
        {"question": "Is B the substance of which A is made?", "answer": True},
        {"question": "Is B part of A's composition?", "answer": True},
        {"question": "Does B form A?", "answer": True},
        {"question": "Is A formed from B?", "answer": True},
        {"question": "Is B used to make A?", "answer": True},
        {"question": "Is B a component of A?", "answer": True},
        {"question": "Does A include B as a material?", "answer": True},
        {"question": "Is A composed of B?", "answer": True},
        {"question": "Is B an element of A?", "answer": True},
        {"question": "Is B the main material of A?", "answer": True},
        {"question": "Is A built using B?", "answer": True},
        {"question": "Is A partially made of B?", "answer": True},
        {"question": "Is B integral to A?", "answer": True},
        {"question": "Is A primarily made of B?", "answer": True},
        {"question": "Does B constitute A?", "answer": True},
        {"question": "Is B the substance that makes up A?", "answer": True},
        {"question": "Is A not made of B?", "answer": False},
        {"question": "Does A consist of something other than B?", "answer": False},
        {"question": "Is B not a material in A?", "answer": False},
        {"question": "Is A constructed from something other than B?", "answer": False},
        {"question": "Is B absent from A's composition?", "answer": False},
        {"question": "Is B not part of A?", "answer": False},
        {"question": "Does B fail to form A?", "answer": False},
        {"question": "Is A formed from a material other than B?", "answer": False},
        {"question": "Is B not used to make A?", "answer": False},
        {"question": "Is B missing from A?", "answer": False},
        {"question": "Does A not include B as a material?", "answer": False},
        {"question": "Is A composed of something other than B?", "answer": False},
        {"question": "Is B not an element of A?", "answer": False},
        {"question": "Is B absent as a main material of A?", "answer": False},
        {"question": "Is A not built using B?", "answer": False},
        {"question": "Is A not partially made of B?", "answer": False},
        {"question": "Is B irrelevant to A?", "answer": False},
        {"question": "Is A primarily made of something other than B?", "answer": False},
        {"question": "Does B not constitute A?", "answer": False},
        {"question": "Is B not the substance that makes up A?", "answer": False},
        {"question": "Is A unrelated to B?", "answer": False},
        {"question": "Is A made of C instead of B?", "answer": False},
        {"question": "Is B absent from the makeup of A?", "answer": False},
        {"question": "Does A contain materials other than B?", "answer": False},
        {"question": "Is A not formed from B?", "answer": False},
        {"question": "Is B missing from A's structure?", "answer": False},
        {"question": "Does A include something else besides B?", "answer": False},
        {"question": "Is B not part of what A is made of?", "answer": False},
        {"question": "Is A created without B?", "answer": False},
        {"question": "Is B non-existent in A?", "answer": False},
        {"question": "Is B not part of the components of A?", "answer": False},
        {"question": "Does A lack B entirely?", "answer": False},
        {"question": "Is A built from something other than B?", "answer": False},
        {"question": "Is B not included in A?", "answer": False},
        {"question": "Does A fail to include B?", "answer": False},
        {"question": "Is A not constructed from B?", "answer": False},
        {"question": "Is B irrelevant to the composition of A?", "answer": False},
        {"question": "Is A unrelated to B as a material?", "answer": False},
        {"question": "Is B absent from what A is made of?", "answer": False},
        {"question": "Is A not formed with B?", "answer": False},
        {"question": "Is B missing as a part of A?", "answer": False},
        {"question": "Is A not composed of B?", "answer": False},
        {"question": "Is B not a component of A?", "answer": False},
        {"question": "Is B not used in the making of A?", "answer": False},
        {"question": "Does A include materials excluding B?", "answer": False},
        {"question": "Is B irrelevant to the construction of A?", "answer": False},
        {"question": "Is A created without using B?", "answer": False}
    ],
    "Causes": [
        {"question": "Does A cause B?", "answer": True},
        {"question": "Is B a result of A?", "answer": True},
        {"question": "Can A lead to B?", "answer": True},
        {"question": "Does A bring about B?", "answer": True},
        {"question": "Is B an effect of A?", "answer": True},
        {"question": "Is B triggered by A?", "answer": True},
        {"question": "Is A responsible for B?", "answer": True},
        {"question": "Does A produce B?", "answer": True},
        {"question": "Is B a consequence of A?", "answer": True},
        {"question": "Does A result in B?", "answer": True},
        {"question": "Is B caused by A?", "answer": True},
        {"question": "Is B due to A?", "answer": True},
        {"question": "Does A generate B?", "answer": True},
        {"question": "Is B an outcome of A?", "answer": True},
        {"question": "Is B initiated by A?", "answer": True},
        {"question": "Does A induce B?", "answer": True},
        {"question": "Is B brought about by A?", "answer": True},
        {"question": "Is B a product of A?", "answer": True},
        {"question": "Is A the cause of B?", "answer": True},
        {"question": "Does A create B?", "answer": True},
        {"question": "Does A not cause B?", "answer": False},
        {"question": "Is B unrelated to A?", "answer": False},
        {"question": "Does A fail to lead to B?", "answer": False},
        {"question": "Is B not a result of A?", "answer": False},
        {"question": "Is B unaffected by A?", "answer": False},
        {"question": "Does A not bring about B?", "answer": False},
        {"question": "Is A unrelated to B?", "answer": False},
        {"question": "Does A not produce B?", "answer": False},
        {"question": "Is B independent of A?", "answer": False},
        {"question": "Does A not result in B?", "answer": False},
        {"question": "Is B not caused by A?", "answer": False},
        {"question": "Is B not due to A?", "answer": False},
        {"question": "Does A fail to generate B?", "answer": False},
        {"question": "Is B not an outcome of A?", "answer": False},
        {"question": "Is B not initiated by A?", "answer": False},
        {"question": "Does A fail to induce B?", "answer": False},
        {"question": "Is B not brought about by A?", "answer": False},
        {"question": "Is B not a product of A?", "answer": False},
        {"question": "Is A not the cause of B?", "answer": False},
        {"question": "Does A fail to create B?", "answer": False},
        {"question": "Is B unaffected by the actions of A?", "answer": False},
        {"question": "Is B unrelated to the effect of A?", "answer": False},
        {"question": "Does A not lead to B in any case?", "answer": False},
        {"question": "Is B independent from A?", "answer": False},
        {"question": "Does A not influence B?", "answer": False},
        {"question": "Is B never caused by A?", "answer": False},
        {"question": "Does A fail to bring B about?", "answer": False},
        {"question": "Is B unrelated to the consequence of A?", "answer": False},
        {"question": "Does A not produce any B?", "answer": False},
        {"question": "Is B not a consequence of A?", "answer": False},
        {"question": "Is B unaffected by the actions of A?", "answer": False},
        {"question": "Does A never cause B?", "answer": False},
        {"question": "Is B not an effect of A?", "answer": False},
        {"question": "Does A fail to result in B?", "answer": False},
        {"question": "Is B not triggered by A?", "answer": False},
        {"question": "Is A unrelated to creating B?", "answer": False},
        {"question": "Does A not induce any B?", "answer": False},
        {"question": "Is B independent of the action A?", "answer": False},
        {"question": "Does A not bring B into existence?", "answer": False},
        {"question": "Is B unrelated to A’s activity?", "answer": False},
        {"question": "Does A fail to produce the effect B?", "answer": False},
        {"question": "Is B not influenced by A?", "answer": False},
        {"question": "Does A not cause the outcome B?", "answer": False},
        {"question": "Is B unaffected by A’s action?", "answer": False},
        {"question": "Does A fail to create the result B?", "answer": False},
        {"question": "Is B not a result of the activity of A?", "answer": False},
        {"question": "Does A not trigger B?", "answer": False},
        {"question": "Is B not generated by A?", "answer": False},
        {"question": "Does A fail to bring about the result B?", "answer": False},
        {"question": "Is B not produced by A?", "answer": False}
    ],
    "Desires": [
        {"question": "Does A desire B?", "answer": True},
        {"question": "Does A want B?", "answer": True},
        {"question": "Is B something A wishes for?", "answer": True},
        {"question": "Is A aiming to get B?", "answer": True},
        {"question": "Is B a goal of A?", "answer": True},
        {"question": "Is B something A seeks?", "answer": True},
        {"question": "Does A long for B?", "answer": True},
        {"question": "Is B an aspiration of A?", "answer": True},
        {"question": "Is B something A hopes for?", "answer": True},
        {"question": "Is A interested in B?", "answer": True},
        {"question": "Does A crave B?", "answer": True},
        {"question": "Is B something A aims to achieve?", "answer": True},
        {"question": "Does A wish to obtain B?", "answer": True},
        {"question": "Is B something A is seeking?", "answer": True},
        {"question": "Does A pursue B?", "answer": True},
        {"question": "Is B a target of A?", "answer": True},
        {"question": "Does A intend to get B?", "answer": True},
        {"question": "Is B part of A's desires?", "answer": True},
        {"question": "Is A striving for B?", "answer": True},
        {"question": "Does A hope to have B?", "answer": True},
        {"question": "Does A not desire B?", "answer": False},
        {"question": "Does A have no interest in B?", "answer": False},
        {"question": "Is B something A does not want?", "answer": False},
        {"question": "Is A not aiming for B?", "answer": False},
        {"question": "Is B not a goal of A?", "answer": False},
        {"question": "Is B something A avoids?", "answer": False},
        {"question": "Does A not long for B?", "answer": False},
        {"question": "Is B not an aspiration of A?", "answer": False},
        {"question": "Is B something A is indifferent to?", "answer": False},
        {"question": "Is A uninterested in B?", "answer": False},
        {"question": "Does A not crave B?", "answer": False},
        {"question": "Is B not something A aims to achieve?", "answer": False},
        {"question": "Does A not wish to obtain B?", "answer": False},
        {"question": "Is B something A is not seeking?", "answer": False},
        {"question": "Does A not pursue B?", "answer": False},
        {"question": "Is B not a target of A?", "answer": False},
        {"question": "Does A not intend to get B?", "answer": False},
        {"question": "Is B not part of A's desires?", "answer": False},
        {"question": "Is A not striving for B?", "answer": False},
        {"question": "Does A have no hope to have B?", "answer": False},
        {"question": "Does A avoid desiring B?", "answer": False},
        {"question": "Is A indifferent to B?", "answer": False},
        {"question": "Does A not seek B?", "answer": False},
        {"question": "Is B irrelevant to A's desires?", "answer": False},
        {"question": "Does A lack interest in B?", "answer": False},
        {"question": "Is B not a target for A?", "answer": False},
        {"question": "Does A not aim for B?", "answer": False},
        {"question": "Is B outside A's aspirations?", "answer": False},
        {"question": "Does A not long to obtain B?", "answer": False},
        {"question": "Is B something A disregards?", "answer": False},
        {"question": "Does A have no wish for B?", "answer": False},
        {"question": "Is B not desired by A?", "answer": False},
        {"question": "Does A avoid pursuing B?", "answer": False},
        {"question": "Is B not sought by A?", "answer": False},
        {"question": "Does A not hope for B?", "answer": False},
        {"question": "Is A uninterested in obtaining B?", "answer": False},
        {"question": "Does A not strive for B?", "answer": False},
        {"question": "Is B not relevant to A's goals?", "answer": False},
        {"question": "Does A have no aim to achieve B?", "answer": False},
        {"question": "Is A indifferent towards B?", "answer": False},
        {"question": "Does A not intend to pursue B?", "answer": False},
        {"question": "Is B outside the desire of A?", "answer": False},
        {"question": "Does A not seek to achieve B?", "answer": False},
        {"question": "Is B something A does not aim for?", "answer": False},
        {"question": "Does A lack the desire for B?", "answer": False},
        {"question": "Is A not aiming to get B?", "answer": False},
        {"question": "Is B irrelevant to what A wants?", "answer": False}
    ],
    "DistinctFrom": [
        {"question": "Is A distinct from B?", "answer": True},
        {"question": "Are A and B different?", "answer": True},
        {"question": "Is A not the same as B?", "answer": True},
        {"question": "Do A and B differ?", "answer": True},
        {"question": "Is B not identical to A?", "answer": True},
        {"question": "Is A separate from B?", "answer": True},
        {"question": "Is A unlike B?", "answer": True},
        {"question": "Are A and B not equal?", "answer": True},
        {"question": "Does A differ from B?", "answer": True},
        {"question": "Is B not the same as A?", "answer": True},
        {"question": "Is A not equivalent to B?", "answer": True},
        {"question": "Is A not comparable to B?", "answer": True},
        {"question": "Is A different in nature from B?", "answer": True},
        {"question": "Is B distinct from A?", "answer": True},
        {"question": "Are A and B not the same entity?", "answer": True},
        {"question": "Is A not B?", "answer": True},
        {"question": "Is B unlike A?", "answer": True},
        {"question": "Are A and B dissimilar?", "answer": True},
        {"question": "Is A not matching B?", "answer": True},
        {"question": "Is B not equivalent to A?", "answer": True},
        {"question": "Is A the same as B?", "answer": False},
        {"question": "Are A and B identical?", "answer": False},
        {"question": "Is A equal to B?", "answer": False},
        {"question": "Do A and B match?", "answer": False},
        {"question": "Is B the same as A?", "answer": False},
        {"question": "Is A not distinct from B?", "answer": False},
        {"question": "Is A similar to B?", "answer": False},
        {"question": "Are A and B alike?", "answer": False},
        {"question": "Does A equal B?", "answer": False},
        {"question": "Is B equivalent to A?", "answer": False},
        {"question": "Is A the same entity as B?", "answer": False},
        {"question": "Is A matching B?", "answer": False},
        {"question": "Are A and B not different?", "answer": False},
        {"question": "Is B identical to A?", "answer": False},
        {"question": "Is A equivalent to B?", "answer": False},
        {"question": "Is A comparable to B?", "answer": False},
        {"question": "Is A like B?", "answer": False},
        {"question": "Are A and B the same?", "answer": False},
        {"question": "Is B not distinct from A?", "answer": False},
        {"question": "Is A not different from B?", "answer": False},
        {"question": "Is A identical to B?", "answer": False},
        {"question": "Do A and B represent the same thing?", "answer": False},
        {"question": "Is B matching A?", "answer": False},
        {"question": "Are A and B equivalent?", "answer": False},
        {"question": "Is A not unlike B?", "answer": False},
        {"question": "Is B the same entity as A?", "answer": False},
        {"question": "Are A and B equal?", "answer": False},
        {"question": "Is A not separate from B?", "answer": False},
        {"question": "Is A identical with B?", "answer": False},
        {"question": "Is B similar to A?", "answer": False},
        {"question": "Are A and B not distinct?", "answer": False},
        {"question": "Is B equivalent to A?", "answer": False},
        {"question": "Is A matching B?", "answer": False},
        {"question": "Do A and B correspond?", "answer": False},
        {"question": "Is A not separate from B?", "answer": False},
        {"question": "Is A not unlike B?", "answer": False},
        {"question": "Is A not dissimilar to B?", "answer": False},
        {"question": "Is A identical in nature to B?", "answer": False},
        {"question": "Are A and B the same thing?", "answer": False},
        {"question": "Is B matching A?", "answer": False},
        {"question": "Is A not different from B?", "answer": False},
        {"question": "Do A and B denote the same?", "answer": False},
        {"question": "Is A identical to B in essence?", "answer": False},
        {"question": "Is B equivalent in nature to A?", "answer": False},
        {"question": "Are A and B indistinguishable?", "answer": False},
        {"question": "Is A the same object as B?", "answer": False},
        {"question": "Is A not unique compared to B?", "answer": False}
    ]
}